### DISCUSSION TITLE
connect to services installed locally but not in the cluster (i.e mysql)

### DISCUSSION THREAD

**Discussion by jaggaer-asalina** [rancher-sandbox/rancher-desktop#1168] [Q&A]
Hi all,
i'm trying creating a local dev environment for my devs based on k8s; i'm able to create local images with nerdctl and deploy them to the local cluster but i really don't know how to make my pods connecting to external local services.
Following my doubts:
- how can i connect to a service installed and running on my laptop ( win10) ? i.e: a local mysql instance installer as a service on my laptop.... or to reach a local Keycloak instance running on my laptop .. instance tha usually i reach with the usual http://localhost:8080/auth address
- i tried creating an external services like this
```
kind: Service
apiVersion: v1
metadata:
  name: ext-service
  namespace: j1p
spec:
  type: ExternalName
  externalName: 127.0.0.1
```
but from what i know i cannot use a 127.0.0.1 ip address...
is there anyone who could give me some suggestions?
