### DISCUSSION TITLE
Question: What workflows do developers want from Rancher Desktop?

### DISCUSSION THREAD

**Discussion by agracey** [rancher-sandbox/rancher-desktop#1189] [Q&A]
After the 1.0 release, we will move into adding more features to Rancher Desktop. It would be helpful to us to know how people are using our tools!

For anyone working with containers as a developer, what workflows do you use?

If you can, please let us know:
- How are you using containers
- What your workflow is
- If you use standalone containers, Kubernetes, or both

Thank you for helping us make Rancher Desktop a better experience for everyone!

**Comment by atoy3731** [comment]
I'm not sure of feasibility, but when I'm developing a new Docker image, I still generally use docker-compose for quick-and-dirty inter-networked, multi-container testing. For instance, if my image requires a Postgres image, it's way simpler to test locally with docker-compose as opposed to all of the necessary K8s manifests (deployments, services, ingress, etc.)

For instance:
```
version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin

  test-app:
    image: test-app:1.0
    container_name: test-app
    hostname: test-app
    ports:
      - "8080:80"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: test
      DB_USER: admin
      DB_PASS: password
```
