### DISCUSSION TITLE
How to expose Rancher-Desktop docker daemon on tcp://0.0.0.0:2375

### DISCUSSION THREAD

**Discussion by abcarcol** [rancher-sandbox/rancher-desktop#2304] [Q&A]
I have already created a configuration file at /etc/docker/daemon.json with the following content:

{
  "hosts": [
    "tcp://0.0.0.0:2375"
  ]
}

However, this is in conflict with the parameters used in the command line, as shown in the error below:

unable to configure the Docker daemon with file /etc/docker/daemon.json: the following directives are specified both as a flag and in the configuration file: hosts: (from flag: [unix:///mnt/wsl/rancher-desktop/run/docker.sock unix:///var/run/docker.sock], from file: [tcp://0.0.0.0:2375])
Error: timed out waiting for /mnt/wsl/rancher-desktop/run/docker.sock to exist
Usage:
  wsl-helper docker-proxy start [flags]

Flags:
      --endpoint string   Dockerd socket endpoint (default "/mnt/wsl/rancher-desktop/run/docker.sock")
  -h, --help              help for start
      --port uint32       Vsock port to listen on (default 23752375)

Global Flags:
      --verbose count   enable extra logging

How can I restart the docker daemon in the Rancher-Desktop WSL2 distro to use the daemon.json config instead of the mentioned flags?. 

Many thanks in advance,
Abel.

**Comment by jandubois** [comment]
I've created enhancement request #2851 from this question; I don't think this is currently possible.

**Comment by dermot-hardy** [comment]
I'm running this to workaround the problem:

    docker container run -dt --name expose-docker-on-2375 --network=host -v /var/run/docker.sock:/var/run/docker.sock --restart=always rancher/socat-docker

It seems to work quite well.

**Reply by jiri-otoupal** [reply]
It does not work for me:
`docker: error during connect: Post "http://localhost:2375/v1.24/containers/create?name=expose-docker-on-2375": dial tcp [::1]:2375: connectex: No connection could be made because the target machine actively refused it.`

**Reply by dermot-hardy** [reply]
Run `wsl -d rancher-desktop` first, so that you're running it from within the Rancher Desktop distribution.

**Reply by mung3r** [reply]
When I test within rancher-desktop distro, it works. From powershell (or the host side) it still seems like it's not exposed or blocked.

**Reply by mung3r** [reply]
This works for me now. There was some other windows process that was using port 2375. Once I sorted that out, I was able to test successfully from the host side.

**Reply by moikaturns** [reply]
Thanks. The image ```rancher/socat-docker``` looks deprecated on latest docker engine so need an alternative image e.g.
```
docker run -d --restart always -v /var/run/docker.sock:/var/run/docker.sock -p 2375:2375 --name socat rycus86/docker-socat
```

**Reply by DanAIDev** [reply]
> Thanks. The image `rancher/socat-docker` looks deprecated on latest docker engine so need an alternative image e.g.
> 
> ```
> docker run -d --restart always -v /var/run/docker.sock:/var/run/docker.sock -p 2375:2375 --name socat rycus86/docker-socat
> ```

Thank you, it works for me, at least for now.

**Comment by MrBuddyCasino** [comment]
Yeah this is annoying. I'm using Testcontainers and it can't talk to a remote Rancher Desktop, because [docker-java](https://github.com/docker-java/docker-java) does not support the ssh transport, which could work around this.

It is also possible to bind to all network interfaces, not just 127.0.0.1:
```
docker run -d --restart=always \
    -p 0.0.0.0:2375:2375 \
    -v /var/run/docker.sock:/var/run/docker.sock \
    alpine/socat \
    tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock
```

**Comment by Coleganet** [comment]
I have a External App install and manage a container and before is not working with Rancher Desktop and for me is a problem well is a very easy system to do it . Deactivate traefik in rancher desktop and the spining .
create docker compose file
notepad docker-compose.yml
if you like more nano install with choco o winget I love nano :))

copy and paste the next


```
version: "3.3"

services:

  traefik:
    image: "traefik:v3.1"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"
	  
```
done now you just start with 

docker compose up -d

The trick is you have this Lines

```
 extra_hosts:
      - "host.docker.internal:host-gateway"
```

Us root look in C:\Windows\System32\drivers\etc
and edit the hosts file , (Make a copy of the file in case before anything)
Add  them the next when the IP is the IP of your Rancher Desktop . Just check your Ip before anything 

# Added Docker Desktop
172.20.0.3 host.docker.internal
172.20.0.3 gateway.docker.internal

save and exit from Rancher Desktop / Reboot Windows 
Now Traefik is indeed working again just go to http://localhost:8080/dashboard/#/ and the best the daemon of docker desktop is exposed 
Not need for any ports setup or any modifications that work perfect in any port or ip 

For any others updates Follow the project https://github.com/Coleganet/Daemon.git
