### DISCUSSION TITLE
Create pod from local registry failed with ErrImageNeverPull

### DISCUSSION THREAD

**Discussion by tanyeun** [rancher-sandbox/rancher-desktop#3688] [Q&A] [answered]
Hi guys,

I installed an image through the following command:
> nerdctl load < nginx.latest

when I tried to create a pod using the following command:
> kubectl apply -f test.yaml

it showed ErrImageNeverPull
> kubectl get pods

```
NAME                              READY   STATUS              RESTARTS   AGE
test-5d5754558d-rhxgc             0/1     ErrImageNeverPull   0          4s
```

but I do have this image on nerdctl images.
```
REPOSITORY                TAG           IMAGE ID        CREATED        PLATFORM       SIZE         BLOB SIZE  
nginx                     latest        0047b729188a    2 hours ago    linux/amd64    149.4 MiB    54.2 MiB
```

any ideas?

heres my test.yaml file:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test
          image: nginx:latest
          imagePullPolicy: Never
          stdin: true
          tty: true
          command:
            - /bin/bash
          ports:
            - containerPort: 80
              protocol: TCP
          env: null
      restartPolicy: Always
```

I am running Rancher Desktop on Windows 10.
