### DISCUSSION TITLE
How to set INSTALL_K3S_EXEC?

### DISCUSSION THREAD

**Discussion by FlappiTomic** [rancher-sandbox/rancher-desktop#5048] [Q&A] [answered]
Hello,

I'd like to set INSTALL_K3S_EXEC to customize k3s, specifically `INSTALL_K3S_EXEC="--tls-san x.x.x.x"` to let others connecting to the k3s cluster created by Rancher Desktop.
I tried putting into override.yaml at `~/Library/Application Support/rancher-desktop/lima/_config/override.yaml` but did not work.
Here is my override.yaml:
```
env:
  INSTALL_K3S_EXEC: --tls-san x.x.x.x
```

I also tried with:
```
provision:
  - mode: system
    script: |
      #!/bin/sh
      echo "INSTALL_K3S_EXEC=\"--tls-san x.x.x.x\"" > /etc/environment
```
Did not work out either.

I wonder what is the proper way to set this? I read in the repo that there is a `K3S_EXEC` but I think it is for k3s post installation, not for the install itself. `INSTALL_K3S_EXEC` is what suggested by official k3s documentation.
