### DISCUSSION TITLE
How can I create a deployment from a local image in the rancher cluster?

### DISCUSSION THREAD

**Discussion by GersonTrj** [rancher-sandbox/rancher-desktop#6787] [Q&A] [answered]
I am new to rancher desktop and I am trying to set up a local cluster to test my application but I am a bit lost on how to do this. 

What I have done so far:

1. I made sure that I am using the rancher context: `kubectl config use-context rancher-desktop`
2. I have built my dockerfile: `docker build -t testapp .`
3. I created my deployment: `kubectl create deployment testapp --image=testapp`

An now, I see in the rancher-desktop dashboard that I have this deployment but the pod is in error trying to pull the image from the docker hub, even tho it is a local image. 

A bit of guidance will be appreciated =)

**Comment by mook-as** [comment, marked as answer]
Note that if your image is using the (default) `latest` tag, Kubernetes will by default try to pull the image every time it starts (leading to a failure to pull the image); please try with a different tag (i.e. `docker build -t testapp:something .`) instead.  Alternatively, set a `ImagePullPolicy` that isn't `always`.  Please refer to [upstream Kubernetes documentation](https://kubernetes.io/docs/concepts/containers/images/#imagepullpolicy-defaulting) for details.

**Comment by lmhajdukd** [comment]
I've created a local image using:
`docker build . -t web:test`

Then I created deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  template:
    metadata:
      labels:
        io.kompose.service: web
    spec:
      containers:
        - image: web:test
          name: web
          ports:
            - containerPort: 5000
              protocol: TCP
      restartPolicy: Always
```

Effect is:
<img width="494" alt="image" src="https://github.com/user-attachments/assets/10d58cb3-d96a-465d-86f5-91c1d0d3b1c2" />

Image is not found. (MacOS ARM, rancher running single master node, using apple virtualization)

I can push it to external registry and pull it from there to rancher-node but its a pointless round-trip. Question is - How to use local docker registry as source for pods in rancher k8s?
