### DISCUSSION TITLE
Port-forwarding other than `8080:80` does not work

### DISCUSSION THREAD

**Discussion by toshohirasawa** [rancher-sandbox/rancher-desktop#6986] [Q&A]
I can successfully set port forwarding from 80 (container) to 8080 (host) but failed to use ports other than 8080 as the host port.
Once I set ports like `8081:80`, my Chrome says, "This site can’t be reached" when I access `http://localhost:8081/`.

OS: macOS 14.4.1
Rancher Desktop: 1.13.1
Kubernetes: 1.29.4

Settings changed from default:
- Virtual Machine Type: VZ
- Mount Type: virtiofs

Here is the docker-compose.yml I used:

```yaml
version: '3'
services:
  dokuwiki:
    image: lscr.io/linuxserver/dokuwiki:latest
    container_name: dokuwiki
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - './persist:/config'
    ports:
      - 8081:80
    restart: unless-stopped
```

I'm not sure whether the Docker image or Rancher desktop caused the problem, and I don't know how to distinguish the cause.
Any advice will be appreciated.
Thanks!
