### ISSUE TITLE
[macOS] Stuck in Waiting for Kubernetes after update to 0.7

### ISSUE THREAD

**Issue by yuchanns** [rancher-sandbox/rancher-desktop#1129]
### Rancher Desktop Version

0.7

### Rancher Desktop K8s Version

1.21.7

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Actual Behavior

After manually updated my app from 0.7.0-beta to 0.7.0 (replace /Applications/Rancher\ Desktop.app), it stuck on Waiting for Kubernetes API... forever.

I check the k3s.log and got `invalid node ip, unable to get global unicast ip from interface name: can't find ip for interface rd0.`

My active network interface is `en0`, and checkout that interface in file `~/Library/Application\ Support/rancher-desktop/lima/_config/networks.yaml` is `en0`, which means no need to change.

I stop and restart Rancher Desktop but nothing fixed.

### Steps to Reproduce

Update the app version to 0.7.0.

### Result

Stuck on `Waiting for Kubernetes API...`.

### Expected Behavior

Start K3S successful.

### Additional Information

```sh
system_profiler SPNetworkDataType -json | jq -r '.SPNetworkDataType[] | select(.interface) | @text "\(._name):\(.interface)"'

USB Controls:usbmodem908NTNH9V1192
Ethernet Adapter (en4):en4
Ethernet Adapter (en5):en5
Ethernet Adapter (en6):en6
AX88179A:en8
Wi-Fi:en0
iPhone:en7
Thunderbolt Bridge:bridge0
```

Here I paste the file content:
```yaml
paths:
  vdeSwitch: /opt/rancher-desktop/bin/vde_switch
  vdeVMNet: /opt/rancher-desktop/bin/vde_vmnet
  varRun: /private/var/run/rancher-desktop-lima
  sudoers: /private/etc/sudoers.d/rancher-desktop-lima
group: staff
networks:
  shared:
    mode: shared
    gateway: 192.168.205.1
    dhcpEnd: 192.168.205.254
    netmask: 255.255.255.0
  bridged:
    mode: bridged
    interface: en0
  host:
    mode: host
    gateway: 192.168.206.1
    dhcpEnd: 192.168.206.254
    netmask: 255.255.255.0
```
And log files
[log.tar.gz](https://github.com/rancher-sandbox/rancher-desktop/files/7733385/log.tar.gz)
