### ISSUE TITLE
Nerdctl can't find .env file

### ISSUE THREAD

**Issue by benjaminpreiss** [rancher-sandbox/rancher-desktop#1213]
### Rancher Desktop Version

0.7.1

### Rancher Desktop K8s Version

1.22.5

### What operating system are you using?

Other (specify below)

### Operating System / Build Version

WSL2 debian on Windows 10 professional

### What CPU architecture are you using?

x64

### Actual Behavior

nerdctl compose can not find my .env file even though specifying it via the --env-file option

### Steps to Reproduce

Create a basic docker-compose.yml e.g.

```yml
version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
  redis:
    image: "redis:alpine"
```

Create a .env file in the same directory. e.g.

```env
# .env file
PROJECT_NAME=test_project
```

Run command `nerdctl compose -f ./docker-compose.yml config --env-file ./.env`

### Result

I get an error "FATA[0000] Couldn't find env file: ./.env"

### Expected Behavior

The config should be displayed according to the docker-compose.yml
