### ISSUE TITLE
Nerdctl WSL linux bind mount not working in docker-compose

### ISSUE THREAD

**Issue by benjaminpreiss** [rancher-sandbox/rancher-desktop#1338]
### Rancher Desktop Version

Version: 1.0.0-beta.1

### Rancher Desktop K8s Version

1.22.5

### What operating system are you using?

Other (specify below)

### Operating System / Build Version

Windows 10 Pro, WSL2 debian

### What CPU architecture are you using?

x64

### Actual Behavior

My volume bind mounts in the docker-compose are ignored and cause the app to crash.

### Steps to Reproduce

1. create the following file structure:

```
- docker-compose.yml
- myapp/
- - volume/
```

2. The docker-compose should look like this:

```yml
version: "3.9"
services:
  frontend:
    image: node:lts
    volumes:
      - ./myapp/volume:/home/node/app
```

3. run `nerdctl compose -f ./docker-compose.yml up --build`

### Result

I get the following output:

![image](https://user-images.githubusercontent.com/28349122/151197305-700f90c9-88ea-485b-b132-8b0bc1e46fce.png)

### Expected Behavior

This should successfully run and build a container.

**Comment by benjaminpreiss** [comment]
#1307

**Comment by evertonlperes** [comment]
Hi @benjaminpreiss 
Thanks for filing this issue.
Have you faced the same behaviour using `moby/dockerd` container runtime?

You can pick between `containerd` or `dockerd` on Kubernetes Settings tab.

**Comment by benjaminpreiss** [comment]
@evertonlperes Hmm - I just tried. When I switch to moby and run `docker-compose up --build` I get the following error:

```
bash: docker-compose: command not found
```

**Comment by evertonlperes** [comment]
> @evertonlperes Hmm - I just tried. When I switch to moby and run `docker-compose up --build` I get the following error:
> 
> 
> 
> ```
> 
> bash: docker-compose: command not found
> 
> ```

Gotcha.
If you're using any package management (scoop, chocolatey, and etc), try to install ‘docker-compose‘.
RD does not install docker-compose by default, requiring a manual installation.

**Comment by benjaminpreiss** [comment]
@evertonlperes Ah, yeah I just saw that there is a pull request out there about that: https://github.com/rancher-sandbox/rancher-desktop/pull/1372

**Comment by benjaminpreiss** [comment]
@evertonlperes I guess with moby it works...

![image](https://user-images.githubusercontent.com/28349122/151716150-0fccaa45-1b49-4bba-ba65-59fb0238df98.png)

**Comment by evertonlperes** [comment]
Thanks for sharing @benjaminpreiss 
Unfortunately, I cannot reproduce the error on `nerdctl`.

Looks like you have an error on your mount paths in your docker-compose file. 
As you're using your docker-compose file, outside of your project folder, you need to configure it accordingly.

Here's an example of a volume mount, where the docker-compose is outside of the project folder:
```yaml
 client:
    container_name: client-container
    build:
      dockerfile: Dockerfile.dev
      context: ./multi-docker/client
    volumes:
      - ./multi-docker/client:/multi-docker/app/volume
```

Closing this issue for now.
Feel free to reopen, if you find another issues.

Thank you.
