### ISSUE TITLE
Issue when rancher try to update kubeconfig

### ISSUE THREAD

**Issue by majstorki88** [rancher-sandbox/rancher-desktop#1384]
### Rancher Desktop Version

1.0.0

### Rancher Desktop K8s Version

1.23.3

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Pro Version	21H2 

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

N/A

### Actual Behavior

When I install Rancher Decktop, shift between docker CLI and containerd, or reset kubernetes, get following error:

![image](https://user-images.githubusercontent.com/29049188/151570466-37f457ab-5113-4e6e-933e-1cea967a2a6f.png)

Kubeconfig has been updated:

```
apiVersion: v1
kind: Config
clusters:
  - name: rancher-desktop
    cluster:
      server: https://172.26.2.151:6443
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUyTkRNek9ERXhOREl3SGhjTk1qSXdNVEk0TVRRME5UUXlXaGNOTXpJd01USTJNVFEwTlRReQpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUyTkRNek9ERXhOREl3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSSzhIdU51di9mRm5zcGt1OFpaLzZxZ2ZZQ3gzSXRqZkpoN0l3NU5BWmIKNmdZU3F4MlNFVWRJNTFaeVZlaXcxSFVGVFlRNlJ1NzFqRXFHYk5JOXNRSzZvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVU9RaHVTV3BEUXpnN0t5MTRldTR6CnVUTEpNOFV3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQUtxeFFwTnArVFNXODBQTEJteEpqTHdnS29IMjE1S2gKczRlclFPY0ZmOGdQQWlCVEhVZGtnOC9KVDE3cjdoeU12ZHI1NjZRRm41d2pKQnFYMmFTSzNMK1c0Zz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      insecure-skip-tls-verify: false
users:
  - name: rancher-desktop
    user:
      client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrVENDQVRlZ0F3SUJBZ0lJQUpwUXVnZlJxTjh3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOalF6TXpneE1UUXlNQjRYRFRJeU1ERXlPREUwTkRVME1sb1hEVEl6TURFeQpPREUwTkRVME1sb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJDeDVDNk1iSFlsRTRBY0IKQzU1aWR3bWxTMkY1TTNzdUc1WXV6K3hUdTBOeFJuc3o4REpsY2JteTB5NTBuMUp0V2g5eGNLWm5ZUE1tTFhSbQpYUlVBNEIyalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCVE5TMndndVlCRGZtWXlZcjQybklEKzZuMUhnVEFLQmdncWhrak9QUVFEQWdOSUFEQkYKQWlBdW9KWk5saG9SVC9vRVhlLzZmSVlPaHpEUGhzZm4xSEJQMkg2ZEZmNm5kd0loQUo0MGlZcXhjcnd5NEpwZQp5d1BvaVN2RnozVXNyVGlIYTBIZWp1MGVDeWIyCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdFkyeHAKWlc1MExXTmhRREUyTkRNek9ERXhOREl3SGhjTk1qSXdNVEk0TVRRME5UUXlXaGNOTXpJd01USTJNVFEwTlRReQpXakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwWlc1MExXTmhRREUyTkRNek9ERXhOREl3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFUNDBzcitKWUJpWmNqZjVsMXBDSjYrUzdpc1lENjFMbnZISW1WVFkyOWwKaHBUMElIRGcyOUpldE9FNGJQQUpSa25tTktqZmNqZUNrWUw2ZmlTWnJqU0pvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXpVdHNJTG1BUTM1bU1tSytOcHlBCi91cDlSNEV3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQUp3b1lYZXM0TTQvZXNqaVZCSlpmOXRVbU91WVloQ2MKMVFYQ1l3UFE2VlpCQWlCemhXbFZyQlNmanlVejh0cGNlZjRnTUEzL3RQVGN0M05jUkd6all1Rnp4QT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSU9uQjMrSHFrbHUwc3hCOGgzQnVmaDRMUkk4S2R4MjBPY20xUWQ2WWliWXdvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFTEhrTG94c2RpVVRnQndFTG5tSjNDYVZMWVhremV5NGJsaTdQN0ZPN1EzRkdlelB3TW1WeAp1YkxUTG5TZlVtMWFIM0Z3cG1kZzh5WXRkR1pkRlFEZ0hRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
contexts:
  - name: rancher-desktop
    context:
      cluster: rancher-desktop
      name: rancher-desktop
      user: rancher-desktop
preferences: {}
current-context: rancher-desktop

```

Seems like all pods are present and I can get node with command kubectl get nodes

But when I run docker ps for example, got following error:

```
error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json": open //./pipe/docker_engine: The system cannot find the file specified.
```

### Steps to Reproduce

shift between containerd and docker
install rancher desktop
reset kubernetes

### Result

got this error, and I am unable to use docker ps for example,

### Expected Behavior

expect to update kubeconfig and everything should work
