### ISSUE TITLE
headless mode: i want to using rancher-desktop headless mode deploy on vps

### ISSUE THREAD

**Issue by cnmade** [rancher-sandbox/rancher-desktop#1407]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://github.com/rancher-sandbox/rancher-desktop/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

rancher-desktop need GUI windows

### Proposed Solution

provided non-GUI , like cli interface
that we can install them on vps or no GUI desktop window

We developed on local GUI desktop environment,
Then deploy to remote headless vps or server.

**Comment by mook-as** [comment]
> Headless installation is needed to run in the GitHub action.

Rancher Desktop will _not_ work on GitHub Actions, since they do not support nested virtualization (required for Windows to run WSL, and on mac & Linux to run lima / qemu).  We found this out trying to set up CI.

Please consider running something like k3d on docker (which they have running already, at least on Ubuntu) instead.

**Comment by jandubois** [comment]
> Rancher Desktop will _not_ work on GitHub Actions, since they do not support nested virtualization

I think this is only true for Linux runners (because they use older/cheaper Azure instances that lack support for it).

I don't know about the Windows runners (but I think they use the same Azure instance type, so won't work either), but the macOS runners definitely support it (we use them in Lima CI to run the full tests, but use Cirrus-CI for Linux).

So running headless would work as-is for macOS on Github Actions, but require self-hosted runners on better hardware for Github Actions on Linux and Windows.

**Comment by sehz** [comment]
Our main use case is to deploy Kubernetes on   `macos-11` Github action runner.

**Comment by douglascamata** [comment]
FYI I have created [a Github Action that sets up Docker on macOS runners through Colima](https://github.com/douglascamata/setup-docker-macos-action) (that uses Lima, that uses QEMU... all the same tools that Rancher Desktop uses). But setting it all up with Homebrew takes some precious CI-minutes. 

I would love to see headless/CLI mode in Rancher Desktop to use it in my action.

**Comment by linghengqian** [comment]
> So running headless would work as-is for macOS on Github Actions, but require self-hosted runners on better hardware for Github Actions on Linux and Windows.

- I will say that I am curious about how to test the installation of rancher desktop on the macos runner of github actions. I have a test of the github actions pipeline at https://github.com/linghengqian/windows-env-testcontainers-test/blob/master/.github/workflows/test.yml, which demonstrates how to enable WSL 2 and configure the Docker CLI on windows to connect to the Docker Daemon in WSL2 on the `windows server 2025`/`windows-latest` runner of github actions. I can indeed execute `docker run hello-world:linux` in the Docker CLI on windows to run Linux Containers.

```yaml
name: Test CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  
concurrency:
  group: test-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: 'windows-latest'
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Setup WSL 2 and Ubuntu Linux distribution
        uses: Vampire/setup-wsl@v5
        with:
          distribution: 'Ubuntu-24.04'
          use-cache: 'true'
      - name: Setup Docker daemon on Linux distribution on WSL without GUI
        shell: wsl-bash {0}
        run: |
          sudo apt-get update
          sudo apt-get remove docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc
          sudo apt-get install ca-certificates curl -y
          sudo install -m 0755 -d /etc/apt/keyrings
          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
          sudo chmod a+r /etc/apt/keyrings/docker.asc
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y
          sudo sed -i 's|-H fd://|-H fd:// -H tcp://127.0.0.1:12375|' /usr/lib/systemd/system/docker.service
          sudo systemctl daemon-reload
          sudo systemctl restart docker.service
      - name: Test Docker CLI on Windows Server without GUI
        env:
          DOCKER_HOST: tcp://127.0.0.1:12375
        run: |
          docker version
          docker run hello-world:linux
```

- The only downside is that this test file is not compatible with testcontainers-java, see https://github.com/testcontainers/testcontainers-java/issues/10381 . I am actually more curious about what additional operations rancher desktop does to allow testcontainers-java to recognize the Docker Daemon configured by rancher desktop. It would be great if rancher desktop can be installed directly in the intermediate step of github actions.
