### ISSUE TITLE
traefik ingress using localhost on linux

### ISSUE THREAD

**Issue by dmlond** [rancher-sandbox/rancher-desktop#1668]
### Actual Behavior

When running rancher-desktop on my macbook (intel) I can create a deployment, service, and Ingress, and access the service using 127.0.0.1. I cannot do this on my Ubuntu 20_04 linux with rancher-desktop (both use dockerd)

### Steps to Reproduce

create the following resources in rancher-desktop using kubectl
```
apiVersion: v1
kind: Namespace
metadata:
  name: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  namespace: web
spec:
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami
        image: traefik/whoami
        env:
          - name: WHOAMI_PORT_NUMBER
            value: "8080"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-service
  namespace: web
  labels:
    app: whoami
spec:
  selector:
    app: whoami
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami
  namespace: web
  labels:
    app: whoami
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: whoami.oasis.local.development
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: whoami-service
            port:
              number: 8080
```

create an entry in /etc/hosts mapping whoami.oasis.local.development to 127.0.0.1

curl http://whoami.oasis.local.development

### Result

on the mac, this works, but on linux I get connection refused on port 80

### Expected Behavior

I should see the response from the service
Hostname: whoami-658756b586-zjf65
IP: 127.0.0.1
IP: 10.42.0.17
RemoteAddr: 10.42.0.13:48154
GET / HTTP/1.1
Host: whoami.oasis.local.development
User-Agent: curl/7.64.1
Accept: */*
Accept-Encoding: gzip
X-Forwarded-For: 10.42.0.9
X-Forwarded-Host: whoami.oasis.local.development
X-Forwarded-Port: 80
X-Forwarded-Proto: http
X-Forwarded-Server: traefik-6bb96f9bd8-rfgtf
X-Real-Ip: 10.42.0.9

### Rancher Desktop Version

1.0.1

### Rancher Desktop K8s Version

v1.22.6(stable)

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

Ubuntu

### Operating System / Build Version

20.04

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

deb
