### ISSUE TITLE
can't run docker compose with mongo and mounted volume

### ISSUE THREAD

**Issue by hguerrero** [rancher-sandbox/rancher-desktop#1679]
### Actual Behavior

When trying to run a docker-compose file that uses mongo db with a mounted volume (for persisting data). The volume is mounted in a way that does not allow the container to execute `chown`. 

### Steps to Reproduce

1. docker-compose.yaml: 
```
version: '2'
services:
  mongo:
    image: mongo:3.4.23
    container_name: db
    volumes:
      - "./data:/data/db"
 ```
2. run `docker compose up -d`

### Result

```
[+] Running 1/0
 ⠿ Container db  Recreated                                                                                                                         0.0s
Attaching to db
db  | chown: changing ownership of '/data/db': Permission denied
```

### Expected Behavior

container runs correctly

### Rancher Desktop Version

1.0.1

### Rancher Desktop K8s Version

1.23.3

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Big Sur 11.6.3

### What CPU architecture are you using?

x64
