### ISSUE TITLE
Kube Server IP Address

### ISSUE THREAD

**Issue by iliuta** [rancher-sandbox/rancher-desktop#1845]
### Problem Description

This happens on Windows 11  while connecting to the enterprise VPN (Cisco Any connect)

While being connected on an enterprise VPN, Rancher dektop tries to connect to the Kube API Server ip address when launching.

This leads to an error like this
`Error: connect ETIMEDOUT 172.31.151.118:6443`

However, the kube services look up & running when connecting to the WSL2 rancher-desktop instance.

curl https://172.31.151.118:6443 -v -k works well on WSL2 shell (wsl -d rancher-desktop)

In Windows, the IP is unavailable (timeout).

While in Windows, loading https://localhost:6443 in a browser leads to the same result as in WSL2 shell and therefore seem working.

As a workaround, Il created a new kube context in the ./kube/config file, by copying the existing rancher-desktop and by changing the server address into localhost, instead of 172.31.151.118:6443.

Here is how my config file looks like:
`
```
apiVersion: v1
kind: Config
clusters:
  - name: rancher-desktop
    cluster:
      server: https://172.31.151.118:6443
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUS...
      insecure-skip-tls-verify: false
  - name: rancher-desktop-localhost
    cluster:
      server: https://localhost:6443
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSU...
      insecure-skip-tls-verify: false
users:
  - name: rancher-desktop
    user:
      client-certificate-data: LS0tLS1CRUdJTiBDRVJUSU...
      client-key-data: LS0tLS1CRUdJTiBFQyBQU...
contexts:
  - name: rancher-desktop
    context:
      cluster: rancher-desktop
      name: rancher-desktop
      user: rancher-desktop
  - name: rancher-desktop-localhost
    context:
      cluster: rancher-desktop-localhost
      name: rancher-desktop-localhost
      user: rancher-desktop
preferences: {}
current-context: rancher-desktop-localhost
```
`
Then, when selecting rancher-desktop-localhost context, I was able to work with kube containers.

### Proposed Solution

Would it be possible to change the ip address of the Kube API server to localhost in the generated ./kube/config file in Windows?
Will it work the same?

### Preflight Checklist

- [X] I have searched the [issue tracker](https://github.com/rancher-sandbox/rancher-desktop/issues) for a feature request that matches the one I want to file, without success.
