### ISSUE TITLE
LoadBalancer helper Pod doesn't get removed after originating Service got deleted

### ISSUE THREAD

**Issue by manuel-koch** [rancher-sandbox/rancher-desktop#1957]
### Actual Behavior

I'm using the postgres-operator to spin up a postgres-cluster.
During the deployment a `Service` gets created for my postgres-cluster that has type `LoadBalancer`.
Rancher-Desktop starts spinning a dedicated `Daemonset` with a `Pod` for that functionality and I can access the backend functionality from my local laptop IP address.

Now I throw away the whole postgres-cluster incl its `Pods` and `Services`.
After postgres-cluster has been removed by postgres-operator, still there is this lb `Pod` running that tries to handle the requested `LoadBalancer` stuff.
E.g. `pod/svclb-acid-postgres-cluster-2g7ct`, `daemonset.apps/svclb-acid-postgres-cluster`.

```
$ kubectl get-all | grep -E "postgres-cluster"
configmap/kube-root-ca.crt                                                                                  postgres-cluster   17m        
namespace/postgres-cluster                                                                                                     17m        
pod/svclb-acid-postgres-cluster-2g7ct                                                                       postgres-cluster   16m        
secret/default-token-kjzsp                                                                                  postgres-cluster   17m        
secret/postgres-pod-token-g9fnt                                                                             postgres-cluster   16m        
serviceaccount/default                                                                                      postgres-cluster   17m        
serviceaccount/postgres-pod                                                                                 postgres-cluster   16m        
controllerrevision.apps/acid-postgres-cluster-6c64b47df8                                                    postgres-cluster   16m        
daemonset.apps/svclb-acid-postgres-cluster                                                                  postgres-cluster   16m        
rolebinding.rbac.authorization.k8s.io/postgres-pod                                                          postgres-cluster   16m        
```

### Steps to Reproduce

```sh
# spin-up postgres-operator
$ helm repo add postgres-operator https://opensource.zalando.com/postgres-operator/charts/postgres-operator/
$ kubectl create namespace postgres-operator
$ helm upgrade --wait --install --namespace postgres-operator \
             --values postgres-operator-helm-values.yaml \
             postgres-operator postgres-operator/postgres-operator

# spin-up postgres-cluster
$ kubectl create namespace postgres-cluster
$ kubectl apply -f postgres-cluster.yaml

$ sleep 180

# remove postgres-cluster again
$ kubectl delete -f postgres-cluster.yaml
```

With the following files:

`postgres-cluster.yaml`
```yaml
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  namespace: postgres-cluster
  name: acid-postgres-cluster
  labels:
    team: acid
spec:
  dockerImage: registry.opensource.zalan.do/acid/spilo-cdp-14:2.1-p210
  allowedSourceRanges: null
  databases:
    testdb: testuser
  enableMasterLoadBalancer: true
  numberOfInstances: 3
  postgresql:
    version: "14"
  preparedDatabases:
    testdb:
      extensions:
        timescaledb: public
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
  teamId: acid
  users:
    testuser: []
  volume:
    size: 1Gi
```

`postgres-operator-helm-values.yaml`
```yaml
configLoadBalancer:
  # toggles service type load balancer pointing to the master pod of the cluster
  enable_master_load_balancer: true
```

### Result

During deployment of postgres-cluster a rancher-desktop helper _lb_ `Pod` was started, but not cleanup when the requesting `Service` got destroyed.

### Expected Behavior

Removing of `Service` cleans up all rancher-desktop helper stuff too.

### Rancher Desktop Version

Version: 1.2.1

### Rancher Desktop K8s Version

v1.22.3

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey 12.3 (21E230)

### What CPU architecture are you using?

x64
