### ISSUE TITLE
Include nfs-utils in lima to allow nfs volumeMounts

### ISSUE THREAD

**Issue by raubreywhite** [rancher-sandbox/rancher-desktop#2001]
### Problem Description

Currently, volumeMounts using nfs fail, because lima does not have nfs-utils.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld 
  labels:
    app: helloworld
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld0
        image: ubuntu:latest
        command: ["/bin/sleep", "1h"]
        imagePullPolicy: Never
        securityContext:
          privileged: true
        volumeMounts:
        - name: nfs-volume
          mountPath: "/data"
      volumes:
      - name: nfs-volume
        nfs:
          server: 192.168.1.11
          path: /volume1/data
          readOnly: no 
```

### Proposed Solution

If I run the command (macOS)
`LIMA_HOME="$HOME/Library/Application Support/rancher-desktop/lima" "/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl" shell 0` and then `sudo apk add nfs-utils` I can use nfs volumeMounts.

It would be very nice if nfs-utils was included by default in the lima VM, or if there was a way to specify extra packages that we need in the lima VM.

### Preflight Checklist

- [X] I have searched the [issue tracker](https://github.com/rancher-sandbox/rancher-desktop/issues) for a feature request that matches the one I want to file, without success.
