### ISSUE TITLE
Add support for resolving ingress names on host

### ISSUE THREAD

**Issue by jkreileder** [rancher-sandbox/rancher-desktop#2089]
### Problem Description

Minikube has a [ingress-dns](https://minikube.sigs.k8s.io/docs/handbook/addons/ingress-dns/) addon which allows resolving ingress hostnames on the host. That is, with the add-on and corresponding resolver setup on the host, a ingress like

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
[...]
spec:
  rules:
    - host: dev.some.domain
[...]
```

leads to `dev.some.domain` being resolvable on host.  

As far as I can see, there's no equivalent for this in Rancher Desktop yet. It would be nice to have.

### Proposed Solution

Setup a resolver for ingress host names in kubernetes and expose it to the host.  Not sure how much of minikube's add-on (https://gitlab.com/cryptexlabs/public/development/minikube-ingress-dns/-/tree/master/) is reusable.

### Preflight Checklist

- [X] I have searched the [issue tracker](https://github.com/rancher-sandbox/rancher-desktop/issues) for a feature request that matches the one I want to file, without success.
