### ISSUE TITLE
failing to translate the file path

### ISSUE THREAD

**Issue by gioppoluca** [rancher-sandbox/rancher-desktop#2204]
### Actual Behavior

In a docker-compose I usually use a volume like the block below
```
volumes:
  quarkus_src_vol:
    driver: local
    driver_opts:
      type: none
      device: ./quarkus/src
      o: bind
```
use it in the service like this:
```
  quarcus_dev:
    image: maven:3.6.3-openjdk-11
    volumes:
      - ./quarkus/m2:/root/.m2
      - quarkus_src_vol:/usr/src/mymaven
    working_dir: /usr/src/mymaven/${QUARKUS_PROJECT}
    command: mvn quarkus:dev
    ports:
      - 8080:8080
```
I get this error in windows 10, my dcker-compose is in folder d:/docker/csi_tutorial:
```
Error response from daemon: failed to mount local volume: mount d:/docker/csi_tutorial/quarkus/src:/var/lib/docker/volumes/csi_tutorial_quarkus_src_vol/_data, flags: 0x1000: no such file or directory
```

### Steps to Reproduce

As described above

### Result

Error response from daemon: failed to mount local volume: mount d:/docker/csi_tutorial/quarkus/src:/var/lib/docker/volumes/csi_tutorial_quarkus_src_vol/_data, flags: 0x1000: no such file or directory

### Expected Behavior

Volume mounted in the container

### Additional Information

Posted issue on slack and asked to file issue as considered a bug

### Rancher Desktop Version

1.3.0

### Rancher Desktop K8s Version

NA

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

19041.1415

### What CPU architecture are you using?

x64

### Windows User Only

VPN, enterprise proxy, McAfee antivirus
