### ISSUE TITLE
port forwarding didn't work on the main build

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#2244]
As part of the weekly test plan execution, I installed the [main build](https://github.com/rancher-sandbox/rancher-desktop/actions/runs/2348267350) on my windows machine. I deployed nginx using below commands, when i try **Port Forwarding** from the GUI, nothing seems to be happening.

Steps to reproduce:

- Install the latest [main build](https://github.com/rancher-sandbox/rancher-desktop/actions/runs/2348267350)
- Run below command
```
cat <<EOF | kubectl apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
spec:
  selector:
    matchLabels:
      app: nginx
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
        version: v1
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-app
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
  selector:
    app: nginx
EOF
```
- Try **Port Forwarding** from the GUI

However, Running `kubectl port-forward service/nginx-app 8080:80` from a terminal works.
