### ISSUE TITLE
Forwarding port through UI does not work with k8s service when `targetPort` is a port name and not a number

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/rancher-desktop#2349]
### Actual Behavior

Port forwarding is broken when `targetPort` is a name and not a number.

### Steps to Reproduce

Forwarding a port through the UI when `targetPort` is a number works fine. For example:
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rd-test
  namespace: default
data:
  index.html: "hello world"
---
apiVersion: v1
kind: Pod
metadata:
  name: rd-test
  namespace: default
  labels:
    app: rd-test
spec:
  restartPolicy: Always
  containers:
    - name: server
      image: python:3.10-alpine3.14
      command: ["python", "-m", "http.server"]
      args: ["--directory", "/srv", "80"]
      ports:
        - name: http
          protocol: TCP
          containerPort: 80
      volumeMounts:
        - name: myvolume
          mountPath: /srv
          readOnly: true
  volumes:
    - name: myvolume
      configMap:
        name: rd-test
        items:
          - key: index.html
            path: index.html
---
apiVersion: v1
kind: Service
metadata:
  name: rd-test
  namespace: default
spec:
  selector:
    app: rd-test
  ports:
    - protocol: TCP
      targetPort: 80
      port: 8000
  type: ClusterIP
```
However, when `targetPort` is changed to `http` (which should work, according to the k8s [docs](https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/#ServiceSpec)), forwarding a port appears to work from the UI but the service is unreachable with `curl http://localhost:<port>`, where `port` comes from the UI:
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rd-test
  namespace: default
data:
  index.html: "hello world"
---
apiVersion: v1
kind: Pod
metadata:
  name: rd-test
  namespace: default
  labels:
    app: rd-test
spec:
  restartPolicy: Always
  containers:
    - name: server
      image: python:3.10-alpine3.14
      command: ["python", "-m", "http.server"]
      args: ["--directory", "/srv", "80"]
      ports:
        - name: http
          protocol: TCP
          containerPort: 80
      volumeMounts:
        - name: myvolume
          mountPath: /srv
          readOnly: true
  volumes:
    - name: myvolume
      configMap:
        name: rd-test
        items:
          - key: index.html
            path: index.html
---
apiVersion: v1
kind: Service
metadata:
  name: rd-test
  namespace: default
spec:
  selector:
    app: rd-test
  ports:
    - protocol: TCP
      targetPort: http
      port: 8000
  type: ClusterIP
```

### Result

The port forwarding doesn't work.

### Expected Behavior

The port forwarding should work.

### Additional Information

There is an error message in background.log:
```
2022-06-08T15:46:17.881Z: UnhandledRejectionWarning: Error: Could not find port number for default/rd-test:http
    at Server.<anonymous> (/opt/rancher-desktop/resources/app.asar/dist/app/background.js:29:35986)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Originally this was highlighted by Victor Barbu in slack: https://rancher-users.slack.com/archives/C0200L1N1MM/p1654238136827619.

This also appears to occur on macOS, which is what Victor is using.

### Rancher Desktop Version

1.3.0

### Rancher Desktop K8s Version

1.23.6

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

Ubuntu

### Operating System / Build Version

Pop OS 20.04

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

deb
