### ISSUE TITLE
Document an ingress traefix example

### ISSUE THREAD

**Issue by cmoulliard** [rancher-sandbox/rancher-desktop#2460]
## Request

Document an ingress example part of the rancher desktop documentation. 

The rancher documentation describes how to install the desktop but not at all how we can started using the k8s cluster. As it offers OOTB an ingress controller using Traefix that would be great to have a documentation page similar to - https://kind.sigs.k8s.io/docs/user/ingress/ and an example

```
## To get the Node IP
IP=$(kubectl get node/lima-rancher-desktop -o json | jq -r '.status.addresses[] | select(.type=="InternalIP").address')

## To create a namespace and install a `whoami` example
kubectl create ns demo
cat << EOF | kubectl apply -n demo -f -
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: whoami
  name: whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - image: traefik/whoami:latest
          name: whoami
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-svc
spec:
  type: ClusterIP
  selector:
    app: whoami
  ports:
    - port: 80
---    
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami-http
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: whoami.$IP.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: whoami-svc
                port:
                  number: 80 
EOF

## Curl it 
curl whoami.$IP.nip.io
Hostname: whoami-6d79cc864b-7kmmf
IP: 127.0.0.1
IP: ::1
IP: 10.42.0.42
IP: fe80::e804:41ff:feac:7eef
RemoteAddr: 10.42.0.45:35392
GET / HTTP/1.1
Host: whoami.192.168.205.2.nip.io
User-Agent: curl/7.64.1
Accept: */*
Accept-Encoding: gzip
X-Forwarded-For: 10.42.0.1
X-Forwarded-Host: whoami.192.168.205.2.nip.io
X-Forwarded-Port: 80
X-Forwarded-Proto: http
X-Forwarded-Server: traefik-d497b4cb6-4vkg9
X-Real-Ip: 10.42.0.1

## To delete
kubectl delete all,ingress --all -n demo
```

### Proposed Solution

See the request
