### ISSUE TITLE
`hostpath` volumes are unsupported

### ISSUE THREAD

**Issue by jacobisaliveandwell** [rancher-sandbox/rancher-desktop#2470]
### Actual Behavior

When using a `hostpath` volume, this error is displayed:

```storageclass.storage.k8s.io "hostpath" not found```

### Steps to Reproduce

Create a statefulset with a hostpath volume

```yaml
volumes:
  - name: "tmp"
    hostPath:
      path: "/tmp"
```

### Result

```storageclass.storage.k8s.io "hostpath" not found```

### Expected Behavior

no error

### Additional Information

Related to k3s-io/k3s#75

I understand there is a work around, but it's not an agnostic one - having to specify `local-path`
requires the developer to be very aware that they need to support k3s users. There should
be a storage class called `hostpath` which catches these volume types since they are
extremely common for local development.

### Rancher Desktop Version

1.4.1

### Rancher Desktop K8s Version

1.20.7

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

Ubuntu

### Operating System / Build Version

20.04

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

deb

**Comment by jandubois** [comment]
`hostpath` is not a storage class, so the pod spec is likely incorrect.

Minimal `hostpath` example that works as expected:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: foo
spec:
  containers:
  - image: alpine
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
    name: bar
    volumeMounts:
    - mountPath: /data
      name: baz
  volumes:
  - hostPath:
      path: /Users/jan/tmp
    name: baz
```
