### ISSUE TITLE
proxy-url removed from ~/.kube/config for non-RD clusters

### ISSUE THREAD

**Issue by vrevelas** [rancher-sandbox/rancher-desktop#2515]
### Actual Behavior

I have a handful of contexts in my ~/.kube/config, some of which require a proxy for connectivity. I accomplish this by setting proxy-url for those clusters as follows:
```
apiVersion: v1
kind: Config
clusters:
  - name: my-non-rd-cluster
    cluster:
      proxy-url: http://username:password@proxy.fqdn:8080
      server: https://k8s-url
```
On starting up Rancher Desktop, the proxy-url setting disappears from the file.

### Steps to Reproduce

Add a proxy-url setting to ~/.kube/config for a context other than rancher-desktop, as shown above

### Result

After starting Rancher Desktop, the proxy-url line no longer exists in ~/.kube/config

### Expected Behavior

proxy-url should still exist in ~/.kube/config

### Rancher Desktop Version

1.4.1

### Rancher Desktop K8s Version

1.23.8

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

Ubuntu

### Operating System / Build Version

18.04

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

deb

**Comment by jandubois** [comment]
I can confirm that on macOS as well. I've added the definition above verbatim to my `~/.kube/config` file:

```yaml
clusters:
  - name: my-non-rd-cluster
    cluster:
      proxy-url: http://username:password@proxy.fqdn:8080/
      server: https://k8s-url/
```

After starting RD (wait until the node is running), the entry has been changed to:

```yaml
clusters:
  - name: my-non-rd-cluster
    cluster:
      server: https://k8s-url
      insecure-skip-tls-verify: false
```

Previously reported: https://github.com/rancher-sandbox/rancher-desktop/issues/1503#issuecomment-1035195711
