### ISSUE TITLE
Define the `diagnostics` object and create a couple sample checks (without fix actions for now)

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#2655]
When Rancher Desktop starts up, it will create a `diagnostics` object that contains all the checks defined in the app.

The set of diagnostics will depend on the current configuration. E.g. Kubernetes diagnostics will/can not be run if Kubernetes has been disabled. Therefore diagnostics must be refreshed whenever new preference settings have been applied.

Some checks will only be performed when other checks have passed. E.g. we will only check if the bundled `kubectl` is first on the `PATH` if the `~/.rd/bin` directory is included. So if this pass fails, then fixing it (adding `~/.rd/bin` to the end of the `PATH`) may enable a bunch of additional checks that now may show as failed.

Some checks will still be executed, even when it is known that they will fail with the current configuration. E.g. when administrative access has been denied, the VM will not have a routable IP address. We want to still display a failed check, just in case the user was not aware of this connection. They can then mute the check, if this matches their expectation.

The diagnostics object will only include checks that have been executed, so have a "pass" or "fail" state.

The user can "mute" specific checks, so they will not generate notifications and not be shown by default.

Checks are grouped in categories. These are simply headlines in the diagnostics panel and have no further importance.

Each check has a unique and persistent id. It is used to "mute" a check, and it will not change if the check is moved around, or if strings are localized.

We may have many variants of the same check, e.g. `BASH_KUBECTL_FOUND`, `ZSH_KUBECTL_FOUND`, etc. which will check if the bundled `kubectl` binary is found on the `PATH` in the respective shell. So even if the user mutes the check for one shell, and then switches shells, they will see the alert again for the new shell.

```yaml
diagnostics:
  last_update: timestamp
  categories:
  - title: "PATH settings"
    checks:
    - id: BASH_RDBIN_ON_PATH
      documentation: https://rancherdesktop.io/diagnostics/path#rdbin
      description: "The ~/.rd/bin directory has not been added to the PATH, so commandline utilities are not configured in your bash shell"
      passed: false
      muted: false
      fixes:
      - description: "You have selected manual PATH configuration, you can let Rancher Desktop automatically configure it."
        action: ...  # A callback that would turn on automatic configuration
```

The description for each check will be different for pass/fail state, and should be as specific as possible. So don't use:

> Pass: The RD helm command was found on the PATH.
> Fail: The RD helm command was not found on the PATH.

Instead use:

> Pass: The ~/.rd/bin/helm command was found first on the PATH of the bash shell.
> Fail: The /usr/local/bin/helm file is hiding the RD ~/.rd/bin/helm file on the PATH of the bash shell.

Include as much detail as possible. E.g. the user may have configured `/bin/bash` inside `/etc/passwd`, but is actually using the `fish` shell. So reading the message may remind them about this.
