### ISSUE TITLE
Define a configuration file for external dependencies

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#2657]
The configuration file should be in YAML format, so we can have comments inside (`dependencies.yaml`).

It servers 2 purposes:

1. to specify the current version and download location of each dependency.
2. to find the latest released version of each dependency, so we can detect if an update is available.

Templating in the URLs will make this file easier to maintain, so we should implement all tools needing to process it in TypeScript (because the downloader is already written in it).

```yaml
dependencies:
- name: alpine-lima
  version: 0.24.0
  downloads:
    macos-aarch64:
      url:  https://xxxx/v${version}/...
      checksum: (direct, or another URL)
    linux-x86_64: ...
```

This file only specifies the version and download locations; we still have a special function for every dependency to extract just the required resources from the downloaded file.

Additional fields will be needed for finding the latest available version. They can be defined as part of #2658.
