### ISSUE TITLE
The connection to the server localhost:8080 was refused

### ISSUE THREAD

**Issue by adrianovieira** [rancher-sandbox/rancher-desktop#2722]
### Actual Behavior

Error while trying to use the command `kubectl version` nor any other `kubectl` subcommand.

### Steps to Reproduce

- install *pass gnupg2*
- setup *gpg key* and *pass* 
- Install *Rancher-Desktop.AppImage* on *Fedora-36*.
- start *Rancher Desktop*
- run `kubectl version`

### Result

```
I0810 17:07:45.976259   22954 versioner.go:58] invalid configuration: no configuration has been provided
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:30:46Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

### Expected Behavior

*kubectl* works like a charm.

### Additional Information

**`nerdctl namespace ls`**
<Details>

```
NAME        CONTAINERS    IMAGES    VOLUMES    LABELS
buildkit    0             0         0              
k8s.io      20            16        0   
```
</Details>

**`~/.kube/config`** (autogenerated by RD)
<Details>

```
apiVersion: v1
kind: Config
clusters:
  - name: rancher-desktop
    cluster:
      server: https://127.0.0.1:6443
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJlRENDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUyTmpBeE5UTTVOemd3SGhjTk1qSXdPREV3TVRjMU1qVTRXaGNOTXpJd09EQTNNVGMxTWpVNApXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUyTmpBeE5UTTVOemd3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSMGIxZHVOenBadXUySjAxbUM5alQ3SStIa0ZyZmR0aitWdGpQcGN0MjUKUTJ3N0piUkFjRVNNbjI5Rlp4MDhaU2V2VCtMR3pUNjBQNXIwZHhYVjdYVkhvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVWZCSkUzQ3BwcW5wbmsyLzRKZGZHCkNzMmNtV013Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQU12ZXlBL0hpeTZEdVpvUUlHR0I2RE9SZVFBQXYyRmcKaDdTZnNra0lCR3lkQWlFQWx4Qi9Eanp3ZkFEZjJsMTNNd2cxc0EzQS9rQitWR2ZIY1lQbWcvbHc0SUU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      insecure-skip-tls-verify: false
users:
  - name: rancher-desktop
    user:
      client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrRENDQVRlZ0F3SUJBZ0lJV2FhV2lTakhjVWt3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOall3TVRVek9UYzRNQjRYRFRJeU1EZ3hNREUzTlRJMU9Gb1hEVEl6TURneApNREUzTlRJMU9Gb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJCTW9QRFh6VDJLRWE0VEsKR1haVGVKMnkxclBMTWFycnpxNXJGQzY2N21MaTU1MjNqUisxaTQ4R2VsdnRJRUphaFlSbnVWZ3c2Y1hkOHJJMgpaTVVoaWpDalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCVFdhaUNrcFpUc0JzWUIwQVZ2TXEwVngvb0VIakFLQmdncWhrak9QUVFEQWdOSEFEQkUKQWlBSWNDZHVDUmhOVWhoaHVySjlNeVhwZUliaXYyZVVpcTVuckR2K3k5enVPZ0lnS3ZyZE5mV2RJUjhaVFNPdgo0b200UXFkTUZmN1ZvZHBSaHBvVE5ydmpyQXc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkakNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdFkyeHAKWlc1MExXTmhRREUyTmpBeE5UTTVOemd3SGhjTk1qSXdPREV3TVRjMU1qVTRXaGNOTXpJd09EQTNNVGMxTWpVNApXakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwWlc1MExXTmhRREUyTmpBeE5UTTVOemd3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSQlA5QzQxakZPV0VKOXNrb0ZsWVB2MzhRT3k2N0FFZmFwc3g0cmJVVzgKYVNBbnFuaVVHelRiWVNKZ3U2TW5YUTJHOXJ3ZGdSY24zYUhSNnVGRlA1cmZvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVTFtb2dwS1dVN0FiR0FkQUZiekt0CkZjZjZCQjR3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnT1hhdDZrV0VwRUZOOGU1cEhNRzJlUnBzbm0wOUszMUcKVXFoaXN0UWdkYWdDSUNKNU1VNHVVRXpNcHhhM3JGcWoxZkpWVzRYTzk1SUtsNjFHODBNMnpCc2kKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUhCZS9IYXZNVFpqVEFNcmhVTG1PeFFUL3B3T1BIVkw5KzFxdmRzWTdGTGpvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFRXlnOE5mTlBZb1JyaE1vWmRsTjRuYkxXczhzeHF1dk9ybXNVTHJydVl1TG5uYmVOSDdXTApqd1o2VyswZ1FscUZoR2U1V0REcHhkM3lzalpreFNHS01BPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
contexts:
  - name: rancher-desktop
    context:
      cluster: rancher-desktop
      name: rancher-desktop
      user: rancher-desktop
preferences: {}
current-context: ""
```
</Details>

### Rancher Desktop Version

1.5.0

### Rancher Desktop K8s Version

1,24,3 (stable, lastest)

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Other Linux

### Operating System / Build Version

Fedora-36

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

AppImage
