### ISSUE TITLE
use docker-compose volumes:   WARN[0000] Ignoring: volume: Bind: [CreateHostPath]

### ISSUE THREAD

**Issue by nyufeng** [rancher-sandbox/rancher-desktop#2757]
### Actual Behavior

Unable to mount local directory

### Steps to Reproduce

`nerdctl compose up -d`

```
version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/data
    restart: always
```

### Result

WARN[0000] Ignoring: volume: Bind: [CreateHostPath]
INFO[0000] Ensuring image redis:latest
INFO[0000] Re-creating container web_redis_1

### Expected Behavior

mount ./redis-data to /data

### Additional Information

I noticed that my directory permissions were modified

befter:
![image](https://user-images.githubusercontent.com/9927289/184893366-c163788d-1fb9-4b1c-8563-2d2ab6c49957.png)

`nerdctl compose up -d`  after:  
![image](https://user-images.githubusercontent.com/9927289/184893474-d1cd1061-5581-489b-923b-c93c424a1993.png)

### Rancher Desktop Version

1.5.1

### Rancher Desktop K8s Version

1.23.8

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows11 5.10.102.1-microsoft-standard-WSL2 Ubuntu

### What CPU architecture are you using?

x64
