### ISSUE TITLE
`clusterIP` service ports forwarded via Port Forwarding tab in UI are not forwarded to personal WSL distros

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/rancher-desktop#3326]
### Actual Behavior

Ports forwarded via the Port Forwarding tab in the UI work on the Windows host, but not in personal WSL distros.

### Steps to Reproduce

Create a Pod that serves HTTP and a `clusterIP` service that fronts it by running `kubectl apply -f <file>` on the below manifest:
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rd-test
  namespace: default
data:
  index.html: "hello world"
---
apiVersion: v1
kind: Pod
metadata:
  name: rd-test
  namespace: default
  labels:
    app: rd-test
spec:
  restartPolicy: Always
  containers:
    - name: server
      image: python:3.10-alpine3.14
      command: ["python", "-m", "http.server"]
      args: ["--directory", "/srv", "80"]
      ports:
        - name: http
          protocol: TCP
          containerPort: 80
      volumeMounts:
        - name: myvolume
          mountPath: /srv
          readOnly: true
  volumes:
    - name: myvolume
      configMap:
        name: rd-test
        items:
          - key: index.html
            path: index.html
---
apiVersion: v1
kind: Service
metadata:
  name: rd-test
  namespace: default
spec:
  selector:
    app: rd-test
  ports:
    - protocol: TCP
      targetPort: 80
      port: 8000
      nodePort: 32700
  type: NodePort
```
Then, go to the Port Forwarding tab in the Rancher Desktop UI and forward this port. Ensure that you have a personal WSL distro (i.e. not the Rancher Desktop one) installed and configured to integrate with Rancher Desktop via Preferences > WSL. Note how running `curl http://localhost:<forwardedPort>` works on the Windows host, but not in the personal WSL distro.

### Result

Ports forwarded via the Port Forwarding tab in the UI work on the Windows host, but not in personal WSL distros.

### Expected Behavior

Forwarded ports should be forwarded to personal WSL distros that Rancher Desktop has been configured to integrate with.

### Rancher Desktop Version

1.6.1

### Rancher Desktop K8s Version

1.25.3

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Pro 10.0.19044 Build 19044

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

N/A
