### ISSUE TITLE
Handling of WSL2's automatic port forwarding - why is there are difference between NodePort and LoadBalancer services?

### ISSUE THREAD

**Issue by jgoeres** [rancher-sandbox/rancher-desktop#3730]
Hi all,
we are currently exploring the use of Rancher Desktop (together with other "desktop" K8s distros) to set up local developer environments, where parts of the stack a running containerized inside the K8s environment, and the developer starts his apps from the IDE.
The approach we follow makes heavy use of nodeport and loadbalancer services. 
We observed the behavior of the automatic exposing of ports opened inside the WSL environment on the Windows environment (basically an automatic port forwarding that WSL seems to do). According to our observation, this works fine for any ports directly opened inside the WSL environment (tested with `nc -l`) and also with the node ports of NodePort services - they immediately show up as listening ports on the Windows host, opened by the PID of a process labeled "Microsoft Windows Subsystem for Linux Background Host" (wslhost.exe). 
However, if a service is of type "LoadBalancer" (like that of the nginx-ingress-controller that we use instead of traefik, as it is closer to our prod environments), this service's node port(s) are _not_ exposed. When patching the LoadBalancer service to be a NodePort service, the node ports are immediately exposed on the Windows host. Once we patch it back to type LoadBalancer, ports are again _not_ exposed.

Edit: We noticed that apparently, inside the Rancher Desktop environment, the node ports of a LoadBalancer service, even while being displayed by kubectl, are not opened on the WSL "box", so WSL has nothing to forward here. Node ports of "pure" NodePort services are opened.

We wonder if this is intentional and defined behavior on which we can rely, and what is the rationale behind that behavior. 

Any clarification would be highly appreciated.

THX
J

**Comment by Nino-K** [comment]
Hi @jgoeres thanks for bringing this up. After a quick investigation, I can see that our current release `1.7.0` should also expose the LoadBalancer Service type just like how it does with NodePorts. As you can see [here](https://github.com/rancher-sandbox/rancher-desktop-agent/blob/3e25c470a88c9c88541d8fbc6f192d3287a50362/pkg/kube/servicewatcher.go#L142-L151) in our latest releases we also watch for LoadBalancer types along with NodePorts, whereas our older release ([here](https://github.com/rancher-sandbox/rancher-desktop-agent/blob/5998f077d7c9a88d73e5674ee84fb06578853233/pkg/kube/servicewatcher.go#L132-L136)) does not include that logic. Could you please let me know what version of Rancher Desktop you are using?

**Comment by jgoeres** [comment]
Hi @Nino-K 
We observed this on 1.6.2 (which is what we have in our org's software distribution system) and on 1.7.0. 
It is reproducable: patch a NodePort service to LoadBalancer => node port is no longer shown as LISTENING in Windows, patch it back => node port again LISTENING

**Comment by Nino-K** [comment]
Hi @jgoeres I went ahead and tried to reproduce this on my end. When deploying a `NodePort` service, Rancher Desktop exposes the nodePort on the host side. However, as for the `LoadBalancer` service type rancher desktop exposes the `port` (not to be confused with the `targetPort` or `nodePort`) on the host side. So assuming I have the following deployment:
```
default       my-service        NodePort       10.43.102.219   <none>          80:30007/TCP             66m
default       my-loadbalancer   LoadBalancer   10.43.16.63     172.26.36.167   80:32422/TCP             47m
```
Created with the following manifests:
**my-service.yaml**
```
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: MyApp
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80
      targetPort: 80
      nodePort: 30007
```
**my-loadbalancer.yaml**
```
apiVersion: v1
kind: Service
metadata:
  name: my-loadbalancer
spec:
  selector:
    app.kubernetes.io/name: Mylb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
  type: LoadBalancer
```
When deployed I would see the node port is accessible via `30007` on the windows host e.g
```
> netstat -ant | findstr 30007
  TCP    127.0.0.1:30007        0.0.0.0:0              LISTENING       InHost
```
and as for my load balancer it is exposes via port 80 e.g 
```
> netstat -ant | findstr 80
  TCP    127.0.0.1:80           0.0.0.0:0              LISTENING       InHost 
```
Something to note here, when deploying a load balancer along with traefik you would either need to disable the traefik or define some other port other than port 80, since port 80 will be occupied by traefik. 

Please let me know if this help. Thanks
