### ISSUE TITLE
Document how to specify k3s option overrides

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#3924]
The easiest way to do this is by specifying `K3S_EXEC` in the VM environment.

For Linux and macOS this can be done with an `override.yaml` file (macOS location: `~/Library/Application\ Support/rancher-desktop/lima/_config/override.yaml`):

```yaml
env:
  # enable etcd:
  K3S_EXEC: --cluster-init
```

Info needed:
* override.yaml location on Linux
* how to do it on Windows (via provisioning script?)
