### ISSUE TITLE
Run pod with image from private registry, authenticate with credentials from cred helper specified in docker config

### ISSUE THREAD

**Issue by MajorBreakfast** [rancher-sandbox/rancher-desktop#4226]
### Problem Description

I have the following deployment:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-service
spec:
  selector:
    matchLabels:
      app: example-service
  template:
    metadata:
      labels:
        app: example-service
    spec:
      containers:
        - name: main
          image: europe-docker.pkg.dev/josefbrandl/container-images/example-service:1.0.0
          ports:
            - name: http
              containerPort: 3000
```

My `~/.docker/config.json` looks like this:

```json
{
  "auths": {},
  "credHelpers": {
    "europe-docker.pkg.dev": "gcloud"
  },
  "credsStore": "osxkeychain"
}
```

### Proposed Solution

It'd be great if Kubernetes authenticated the image pull using credentials provided by the `docker-credential-gcloud get` command - as specified in the docker config. `docker pull` already does this.

### Additional Information

I'm aware of various workarounds to this:

- Workaround 1: Run `docker pull europe-docker.pkg.dev/josefbrandl/container-images/example-service:1.0.0` first. This downloads the image and makes it so that Kubernetes doesn't have to. This works.
- Workaround 2: Deploy a image pull secret:
  ```sh
  kubectl create secret docker-registry europe-docker.pkg.dev \
  --docker-server=europe-docker.pkg.dev \
  --docker-username=oauth2accesstoken \
  --docker-password=$(gcloud auth print-access-token) \
  --docker-email=none
  ```
  Then, add the image pull secret to the pod. This also works.

Tested on Rancher Desktop version 1.8.0

Related to https://github.com/rancher-sandbox/rancher-desktop/issues/2401, but there seems to be not yet a dedicated issue for pulling from Kubernetes (I think)
