### ISSUE TITLE
"Containerfile: no such file or directory" using nerdctl on rancher-desktop 1.9.0 tech-preview

### ISSUE THREAD

**Issue by arkanmgerges** [rancher-sandbox/rancher-desktop#4620]
### Actual Behavior

I'm using Rancher Desktop 1.9.0 Tech Preview, and I'm getting error when I try to use `nerdctl compose -f docker-compose.yaml up`
![image](https://user-images.githubusercontent.com/7836805/236626693-bca82f83-68b9-49e2-ac07-7d6a361e7cc1.png)

![image](https://user-images.githubusercontent.com/7836805/236626640-88d9ee8c-1525-4cb9-85aa-c7b250d706ad.png)

But when I switched to use `dockerd` instead of `containerd`, then it worked
![image](https://user-images.githubusercontent.com/7836805/236626707-372f1f02-e43b-45d6-aff1-3eee2d2e3e79.png)

![image](https://user-images.githubusercontent.com/7836805/236626736-c0e35a7e-ab82-4a77-9254-bdfd134a528b.png)

### Steps to Reproduce

I'm not sure if you can reproduce it

1. Inside windows 10 pro wsl2
2. docker-compose.yaml
```yaml
version: "3.8"
services:

#  localstack:
#    image: localstack/localstack:0.11.2
#    container_name: localstack
#    ports:
#      - "4566:4566"
#      - "4567-4584:4567-4584"
#    environment:
#      - SERVICES=s3:4572
#      - EXTRA_CORS_ALLOWED_ORIGINS=file://
#    networks:
#      - comet_backend
#    healthcheck:
#      test:
#        - CMD
#        - curl
#        - localhost:4566/health?reload
#      interval: 5s
#      timeout: 20s
#      retries: 10
#      start_period: 10s
#
#  set-up-localstack:
#    build:
#      context: ./localsetup/set-up-localstack
#    container_name: set-up-localstack
#    networks:
#      - comet_backend
#    depends_on:
#      localstack:
#        condition: service_healthy

  cometjobs:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        build_version: ${BUILD_VERSION:-dev}
    container_name: carbon
    command: uvicorn --host 0.0.0.0 --port 80 main:app --reload --reload-dir "./"
    environment:
      ENV: local_docker
    ports:
      - "8080:80"
    networks:
      - carbon_backend
#    depends_on:
#      localstack:
#        condition: service_healthy
    volumes:
      - ./carbon:/carbon

networks:
  carbon_backend:
```

Dockerfile:
```yaml
# Our base python image
FROM python:3.10-alpine as base


FROM base as deps-builder

RUN apk upgrade apk-tools
RUN apk --no-cache add gcc build-base make
RUN apk --no-cache add libffi-dev

# fix poetry version
ENV POETRY_VERSION=1.4.2 \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    POETRY_VIRTUALENVS_IN_PROJECT=true

RUN wget -O - https://install.python-poetry.org | python
ENV PATH="/root/.local/share/pypoetry/venv/bin:$PATH"

COPY pyproject.toml .
COPY poetry.lock.bkup .

RUN poetry install --no-dev --no-root


# The test image light & beautiful
# contains the whole project and dev dependencies
# to run tests
FROM deps-builder as test
RUN apk upgrade apk-tools && \
    apk --no-cache add gcc build-base make

RUN poetry install --no-root

COPY . .

ARG build_version=dev
ENV VERSION=${build_version}
ENV PATH="/.venv/bin:$PATH"
RUN echo ${VERSION} > .version


# The actual image light & beautiful
# only contains application code & built dependencies
# and without Poetry
FROM base as production
COPY --from=deps-builder /.venv .venv
ENV PATH="/.venv/bin:$PATH"

COPY carbon /carbon

WORKDIR carbon/

ARG build_version=dev
ENV VERSION=${build_version}

RUN echo ${VERSION} > .version

CMD uvicorn \
        --host 0.0.0.0 \
        --port 80 \
        main:app
```

### Result

```bash
nerdctl compose -f docker-compose.yml up
INFO[0000] Creating network nerdctl-tmp1352843295_carbon_backend 
INFO[0000] Creating network nerdctl-tmp1352843295_default 
WARN[0000] build.config should be relative path, got "/mnt/wsl/rancher-desktop/run/nerdctl-tmp.1352843295" 
WARN[0000] Ignoring: volume: Bind: [CreateHostPath]
INFO[0000] Building image nerdctl-tmp1352843295_cometjobs
FATA[0000] lstat /mnt/wsl/rancher-desktop/run/nerdctl-tmp.1352843295/Containerfile: no such file or directory 
FATA[0000] error while building image nerdctl-tmp1352843295_cometjobs: exit status 1

```

### Expected Behavior

`nerdctl compose -f docker-compose.yaml up` should work without throwing an error when using `containerd`

### Rancher Desktop Version

1.9.0 Tech Preview

### Rancher Desktop K8s Version

v1.26.3

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Pro, version: 22H2, OS build:  19045.2846, Experience: Windows Feature Experience Pack 120.2212.4190.0

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None
