### ISSUE TITLE
Unable to start container with secret using docker compose

### ISSUE THREAD

**Issue by jacek-jablonski** [rancher-sandbox/rancher-desktop#4993]
### Actual Behavior

Starting container with declared secret in `docker-compose.yaml` and user set in `Dockerfile` results in error:

```
Error response from daemon: getent unable to find entry "newuser" in passwd database
```

### Steps to Reproduce

Dockerfile:
```
FROM ubuntu
RUN useradd -ms /bin/bash newuser
USER newuser
```

docker-compose.yaml:
```
---
version: "3.6"

services:
  ubuntu:
    build:
      context: .
    secrets:
      - PASSWORD
    command: sh -c 'PASSWORD=$(cat /run/secrets/PASSWORD) echo $PASSWORD'

secrets:
  PASSWORD:
    environment: PASSWORD
```

```
PASSWORD="test" docker compose up
```

### Result

```
Error response from daemon: getent unable to find entry "newuser" in passwd database
```

### Expected Behavior

Container should run and exit without an error echoing `test`.

### Additional Information

Mounting secrets works fine with Docker Desktop and newest OrbStack.

### Rancher Desktop Version

1.9.0

### Rancher Desktop K8s Version

N/A

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

13.4

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None
