### ISSUE TITLE
Unable to mount NFS volumes in RancherDesktop

### ISSUE THREAD

**Issue by UnaiUribarri-TomTom** [rancher-sandbox/rancher-desktop#5154]
### Actual Behavior

When I try to launch a pod that references an NFS volume, it always fails to mount that volume.

### Steps to Reproduce

* Install OpenEBS:
```
helm install openebs openebs/openebs -n openebs --create-namespace --set nfs-provisioner.enabled=true
```
* Create an NFS Storage class:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-storage
  annotations:
    openebs.io/cas-type: nfsrwx
    cas.openebs.io/config: |
      - name: NFSServerType
        value: "kernel"
      - name: BackendStorageClass
        value: "local-path"
provisioner: openebs.io/nfsrwx
reclaimPolicy: Delete
```

* Create a NFS PVC
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-spark-logs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage
  resources:
    requests:
      storage: 10Gi
```

* Use it from a POD
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: nfs-share
      mountPath: /mnt/nfs-share
  volumes:
  - name: nfs-share
    persistentVolumeClaim:
        claimName: nfs-pvc-spark-logs
```

### Result
```
Events:
  Type     Reason       Age               From               Message
  ----     ------       ----              ----               -------
  Normal   Scheduled    15s               default-scheduler  Successfully assigned default/nginx to lima-rancher-desktop
  Warning  FailedMount  7s (x5 over 15s)  kubelet            MountVolume.SetUp failed for volume "pvc-4e769d9d-4282-4ff4-aef5-5630ffb08074" : mount failed: exit status 255
Mounting command: mount
Mounting arguments: -t nfs 10.43.22.94:/ /var/lib/kubelet/pods/74d9a5c8-bb78-4ef3-b0d5-1f70d5366e6c/volumes/kubernetes.io~nfs/pvc-4e769d9d-4282-4ff4-aef5-5630ffb08074
Output: mount: mounting 10.43.22.94:/ on /var/lib/kubelet/pods/74d9a5c8-bb78-4ef3-b0d5-1f70d5366e6c/volumes/kubernetes.io~nfs/pvc-4e769d9d-4282-4ff4-aef5-5630ffb08074 failed: Not supported
```

### Expected Behavior

NFS volume was mounted correctly

### Additional Information

This could be related with https://github.com/k3d-io/k3d/issues/1109#issuecomment-1220374460

I get these errors in k3s.log file:
```
E0712 08:59:57.285672    3588 nestedpendingoperations.go:348] Operation for "{volumeName:kubernetes.io/nfs/74d9a5c8-bb78-4ef3-b0d5-1f70d5366e6c-pvc-4e769d9d-4282-4ff4-aef5-5630ffb08074 podName:74d9a5c8-bb78-4ef3-b0d5-1f70d5366e6c nodeName:}" failed. No retries permitted until 2023-07-12 09:00:29.285632171 +0000 UTC m=+11282.502086599 (durationBeforeRetry 32s). Error: MountVolume.SetUp failed for volume "pvc-4e769d9d-4282-4ff4-aef5-5630ffb08074" (UniqueName: "kubernetes.io/nfs/74d9a5c8-bb78-4ef3-b0d5-1f70d5366e6c-pvc-4e769d9d-4282-4ff4-aef5-5630ffb08074") pod "nginx" (UID: "74d9a5c8-bb78-4ef3-b0d5-1f70d5366e6c") : mount failed: exit status 255
Mounting command: mount
Mounting arguments: -t nfs 10.43.22.94:/ /var/lib/kubelet/pods/74d9a5c8-bb78-4ef3-b0d5-1f70d5366e6c/volumes/kubernetes.io~nfs/pvc-4e769d9d-4282-4ff4-aef5-5630ffb08074
Output: mount: mounting 10.43.22.94:/ on /var/lib/kubelet/pods/74d9a5c8-bb78-4ef3-b0d5-1f70d5366e6c/volumes/kubernetes.io~nfs/pvc-4e769d9d-4282-4ff4-aef5-5630ffb08074 failed: Not supported
E0712 09:00:11.898574    3588 mount_linux.go:231] Mount failed: exit status 255
Mounting command: mount
Mounting arguments: -t nfs 10.43.22.94:/ /var/lib/kubelet/pods/dcce4876-a0ad-4844-b3a3-1a52b6198b76/volumes/kubernetes.io~nfs/pvc-4e769d9d-4282-4ff4-aef5-5630ffb08074
Output: mount: mounting 10.43.22.94:/ on /var/lib/kubelet/pods/dcce4876-a0ad-4844-b3a3-1a52b6
198b76/volumes/kubernetes.io~nfs/pvc-4e769d9d-4282-4ff4-aef5-5630ffb08074 failed: Not supported
```

### Rancher Desktop Version

1.9.1

### Rancher Desktop K8s Version

1.25.11 & 1.27.3

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

Ventura 13.4.1

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None
