### ISSUE TITLE
Applied Network policies do not work as expected

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#5247]
### Actual Behavior

Filing this on behalf of a user who reported the problem on Slack - https://rancher-users.slack.com/archives/C0200L1N1MM/p1690441269491959

Hi all, are NetworkPolicies enforced by default on a Rancher Desktop 1.7 installation? I created two nginx pods and a "forbid all ingress and egress" policy, but the pods can normally talk to each other. Applying the same configuration to a k3s deployed on Ubuntu blocks the traffic.

### Steps to Reproduce

There are two pods and a network policy that blocks everything in the default namespace in this example.

```
apiVersion: v1
kind: Pod
metadata:
  name: pod-a
  labels:
    app: pod-a
spec:
  containers:
  - name: nginx
    image: nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-b
  labels:
    app: pod-b
spec:
  containers:
  - name: nginx
    image: nginx:latest
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: untitled-policy
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress: []
  egress: []
```

```
>kubectl get pod -o wide
NAME    READY   STATUS    RESTARTS       AGE   IP            NODE           NOMINATED NODE   READINESS GATES
pod-a   1/1     Running   1 (6h2m ago)   28h   10.42.0.198   logabn220408   <none>           <none>
pod-b   1/1     Running   1 (6h2m ago)   28h   10.42.0.193   logabn220408   <none>           <none>

>kubectl exec pod-a -- curl 10.42.0.193
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   615  100   615    0     0   750k      0 --:--:-- --:--:-- --:--:--  600k
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
```

### Result

traffic is not blocked despite the applied network policy.

However the same setup works as expected on k3s on Ubuntu as shown below:

```
$ kubectl get pod -o wide
NAME    READY   STATUS    RESTARTS   AGE   IP            NODE        NOMINATED NODE   READINESS GATES
pod-a   1/1     Running   0          30h   10.42.4.156   k3s-delta   <none>           <none>
pod-b   1/1     Running   0          30h   10.42.2.9     k3s-gamma   <none>           <none>

$ kubectl exec pod-a -- curl 10.42.2.9
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to 10.42.2.9 port 80 after 0 ms: Couldn't connect to server
command terminated with exit code 7
```

### Expected Behavior

traffic blocked as per the applied network policy

### Rancher Desktop Version

1.9.1

### Rancher Desktop K8s Version

v1.27.3

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Prefessional

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None
