### ISSUE TITLE
Add ssh port to loadbalancer

### ISSUE THREAD

**Issue by pedropilla** [rancher-sandbox/rancher-desktop#5254]
### Problem Description

When we patch the traefik chart to add an additional entrypoint using privileged ports the update keeps failing cause lack of permissions to bind the low port.

Steps to reproduce:

1. Patch the chart with this code:
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
    - "--entryPoints.tcpep.address=:22/tcp"
```

### Proposed Solution

Probably we'll need another reverse ssh tunnel to deal with port 22 too.
