### ISSUE TITLE
Issue about the Kubernetes config initial from Rancher Desktop

### ISSUE THREAD

**Issue by VatthanachaiW** [rancher-sandbox/rancher-desktop#5946]
### Actual Behavior

After updating to version 1.11.0, the Rancher will always override the Kubernetes config with the error config like this config or sometimes delete the existing config.

### Steps to Reproduce

After installing or updating the Kubernetes config, it will override the incorrect config.

### Result

<img width="683" alt="2023-11-09_09-44-57" src="https://github.com/rancher-sandbox/rancher-desktop/assets/10823133/591da727-f078-4b34-9dd8-d880de4ff7bb">

kubecofig
```
clusters:
    - cluster:
        server: https://kubernetes.docker.internal:6443
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJUGV0Qm95SnRSdDh3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TXpFeE1EY3dOak15TXpoYUZ3MHpNekV4TURRd05qTTNNemhhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURHbTlOcWRYYmRvYkxKWndZM2dmWFlldVprUHZQdC9YVGc5Uys4T0toSnloWlcveHEzc2pGeS9CUnUKN0E4UmpScWs5WE5MaDg2cE1iN0JQWHVCWC85N2JPdlRIS3Fqc0sxQ3lORFdKUFpKK29ZRGJGTGdoa3lUWmNFMAp0MzdYa2xDdEZrMHR2ZGxWRUt0eG1LMm5oRjZMM0pJRFkvOFB6MlU0eHhPc1l0ejlqZGdIZnZHdjFsOFVSZmVICkhxd25EUU1KRUxtQ21qWTViNDNER21iWnk0WDhVMGdaQ3NYak1SRWtvMXExeHM0ZXorY1ZrcWtTdUxtYWM4STEKK0xKUUZGWmRWQ0YvRWxKLzBFV1VWVndxKzZkNVVhMytFbUQyY2dDdHZlWG1GTFJNWmZTYWVNQldjK1lneXZaWQpNSEw0bWltRjYzV0N1dko2Mm56dkk3dWJtK285QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJURXFwQUZ6ZzBvakxxYXFVTkJJVDkwYXJuMVZEQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQjcwTmY5V3ExRQpmWlp4aHFmVzhDTTJnZ21hMmxKWkJheVU2WXlTZ3M0WFJybGl0dUxSa2tYbnM1czN2cmVuS2JadXF0S3RNVElMCkxGc0x2UW1BQ2k0bXN2Z3BrLzRiTWUzUEpqdUJjc2FramtBeCtoR2Q4ajdpaEYxOUN1VGd6TlhDQmtUZTVnTysKRFUwdnljVG5mVldZNENRaWUyeER1QnhVYWdnNmxsUUp0R0RoWm1QOTkrNldGa0VPckl3NmVDS3dhdWdNMTFFVApLTGFHOFJxN1Biem9Vd0g0R0prb2dDOW1ObWl3bVVsNHFnMjU0Y0VXamsyclVVcXVOUmRBNnZkMlJPaHhVQVRECngxL3NjanF0QmorSW9tVW1lWFJ4V1k1UVhoQVhmd1hyNXR3MzZSSWp1OFkyWTVYeGZ5MUNFR2diTHVKY0hoYTgKbkIwc1lsd0JaSVFWCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      name: ""
    - cluster:
        server: https://172.17.85.106:6443
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJlRENDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUyT1RjeE1qWXhNemN3SGhjTk1qTXhNREV5TVRVMU5UTTNXaGNOTXpNeE1EQTVNVFUxTlRNMwpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUyT1RjeE1qWXhNemN3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFUNXduNVFEaC9mVERyMW9GbVJ3ZXU3ajk1ZEVKQzF5WHNPKzlaUDZIVkkKazRuSW1nckNWb1BqYUZ2NFVOTkFqd2RNVFBtUmVmc1dIR2I3QmdERVpWa3RvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVdvYWpXKzdnemZCb1dUNGExNmZoCkIvaG8rVjB3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQUpBaThIenZrT2hiY3hYMWtwWjhidVFnMWxxcS80d3YKT0tIV2VFc3ZWQUN3QWlFQTBtYWUra2szOFlRdVVYTDQwNXR5bStZSUZoUFNGUjVscGtjaG5kL21BdGs9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        insecure-skip-tls-verify: false
      name: rancher-desktop
contexts:
    - name: rancher-desktop
      context:
        cluster: rancher-desktop
        name: rancher-desktop
        user: rancher-desktop
current-context: ""
users:
    - name: rancher-desktop
      user:
        client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrVENDQVRlZ0F3SUJBZ0lJREVqSTd4WEVuTlV3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOamszTVRJMk1UTTNNQjRYRFRJek1UQXhNakUxTlRVek4xb1hEVEkwTVRBeApNVEUxTlRVek4xb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJIZGRuR29pK1BFWHU3QlEKZWx5N3RpWEI1c2J1WGlMTHZjUk8zVVlRRDltZ2YxTEtKZ3ZqRlNIdXZpMXRJVC94aVVtVWRUckhQTENRYnJ0UQo1YzlKL3oralNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCVFhxUU5IakhoUVJxYkxtMTUvZUZYeFFETzlCakFLQmdncWhrak9QUVFEQWdOSUFEQkYKQWlCK1k3bUx0bnJKdnJaMjRUU29NWDFiS0laQTd0WEI0Q1pLNEJkSVpQbDFZZ0loQU1PR0ZvQ3pHdHlkbzFrNwpWQnpabkhYSWhzaC9Hc0V5R0NXQXRTOGlCSlROCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkakNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdFkyeHAKWlc1MExXTmhRREUyT1RjeE1qWXhNemN3SGhjTk1qTXhNREV5TVRVMU5UTTNXaGNOTXpNeE1EQTVNVFUxTlRNMwpXakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwWlc1MExXTmhRREUyT1RjeE1qWXhNemN3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSVDVwZWVCUDUwUlhkRGVwRWE0eW96Y0RYckpwTkJ1TzZaMVYxNUZ4WXIKZ1ZZTXhzRzRrM2Q1c2R2TnIwclNvWWVDZnM2eW1DRjdaUE9wM004OUpmMkdvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVTE2a0RSNHg0VUVhbXk1dGVmM2hWCjhVQXp2UVl3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnZkhlaHpCS1JxM3k0QVZ1dTIyTmkrNmo3R3BJN1UvMmwKQkFnbXExTGNBL0VDSUZ6L3JvbVBWVFpVWUpXVFovcGk5d0hNeitSTDVac3l6MitxckcyeHBkNkYKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
        client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSU9WWGwwWldhTFVGU2hXNlgyM2JZTGNhdWpndk0yWGQvcXE5cWxwV2ZxVTRvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFZDEyY2FpTDQ4UmU3c0ZCNlhMdTJKY0hteHU1ZUlzdTl4RTdkUmhBUDJhQi9Vc29tQytNVgpJZTYrTFcwaFAvR0pTWlIxT3NjOHNKQnV1MURsejBuL1B3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
```
sometimes

### Expected Behavior

I'm not sure about the root cause for the issue

### Rancher Desktop Version

1.11.0

### Rancher Desktop K8s Version

1.27.7

### Which container engine are you using?

Docker Cli

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 22H2 build 22621.2506

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None
