### ISSUE TITLE
Provide a routable IP address on macOS (via vmnet)

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#609]
Once the vde_vmnet binaries are installed (#608), lima can automatically control the network daemons.

To add a shared IP address, the following needs to be added to `lima.yaml`:

```yaml
networks:
- lima: shared
```

Starting and stopping the `vde_vmnet` daemon requires `root` (and `daemon`) privileges. You can check if you have sufficient rights with `limactl sudoers --check`, and if not, create/update the sudoers file with:

```shell
limactl sudoers | sudo tee /etc/sudoers.d/lima
```

We need to customize the `$LIMA_HOME/_config/networks.yaml` file to reference our own vde install location, and we should also use RD-specific names for `varRun` and `sudoers`:

```yaml
paths:
  vdeSwitch: /opt/vde/bin/vde_switch
  vdeVMNet: /opt/vde/bin/vde_vmnet
  varRun: /private/var/run/lima
  sudoers: /private/etc/sudoers.d/lima
```

All these files, and all parent directories up to `/` must only be writable by `root` (and `/var/run` group-writable by `daemon`). None of the files are directories are allowed to be symlinks.

Here is the current `networks.yaml` default for reference (still subject to change):

```yaml
$ cat ~/.lima/_config/networks.yaml
# Paths to vde executables. Because vde_vmnet is invoked via sudo it should be
# installed where only root can modify/replace it. This means also none of the
# parent directories should be writable by the user.
#
# The var_run directory also must not be writable by the user because it will
# include the vde_vmnet pid files. Those will be terminated via sudo, so replacing
# the pid files would allow killing of arbitrary privileged processes.
paths:
  vdeSwitch: /opt/vde/bin/vde_switch
  vdeVMNet: /opt/vde/bin/vde_vmnet
  varRun: /private/var/run/lima
  sudoers: /private/etc/sudoers.d/lima

group: staff

networks:
  shared:
    mode: shared
    gateway: 192.168.105.1
    dhcpEnd: 192.168.105.254
    netmask: 255.255.255.0
  bridged:
    mode: bridged
    interface: en0
    # bridged mode doesn't have a gateway; dhcp is managed by outside network
  host:
    mode: host
    gateway: 192.168.106.1
    dhcpEnd: 192.168.106.254
    netmask: 255.255.255.0
```

It will be written the first time a managed network is referenced, but after that not updated again by lima itself.
