### ISSUE TITLE
Connectivity Issue With Network Tunnelling On

### ISSUE THREAD

**Issue by andry85mae** [rancher-sandbox/rancher-desktop#6108]
### Actual Behavior

Hello,

we try to connect with our container to an sql server istance over VPN Connection.
When the container start there are an error because the sql server is unreachable.

If we turn off the Network tunelling the sql is reacheable but we cannot use host.docker.internal to reach the host.

### Steps to Reproduce

enable Network tunelling

use docker compose to start the container

theare are a connectivity issue with sql server

### Result

A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server: Could not open a connection to SQL Server)

### Expected Behavior

with the Netwrok Tunelling active , the sql is reacheable.

### Rancher Desktop Version

1.11.0

### Rancher Desktop K8s Version

1.27.7

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

FortiClient VPN

**Comment by DummyRick** [comment]
Hi @Nino-K,
I'm responding on behalf of @andry85mae. We are collaborating on the same project.
Currently, we are attempting to simulate an architecture for development purposes using Rancher Desktop.

Here's an overview of our scenario:
- Several containers are running under Rancher Desktop.
- There's an MS SQL Database that is accessible using a VPN.
- A service is running on the host machine and must be reachable from the containers. For this reason, we are attempting to use host.docker.internal within our Docker Compose file to enable Rancher OS containers to target the service.

As mentioned by @andry85mae, it seems like:
- If we turn off Network Tunneling, the SQL is reachable, but we cannot use host.docker.internal to reach the host.
- If we disable Network Tunneling, we can reach the local service using host.docker.internal, but SQL seems unreachable.

To simulate this architecture, we simply run Rancher Desktop and then execute a docker-compose up command.

Here's an example of our Docker Compose file (I cannot share the real one):

```
version: '3'

services:

  my-service:
    image: XXXXXXXX.dkr.ecr.eu-west-1.amazonaws.com/my-service:latest
    pull_policy: always
    environment:
      - LocalService__Uri=http://host.docker.internal:6666
      - ConnectionStrings__SQL='Server=192.168.1.X\MSSQL;Database=DBName;User Id=user;Password=MyFakePass;Encrypt=false;TrustServerCertificate=True'
    ports:
     - "7251:80"
    restart: unless-stopped
    networks:
     - default

networks:
  default:
    driver: bridge
```

A few months ago, we tried the same configuration using Docker Desktop, and it seemed to be working. 

Our doubts are:
- is our docker-compose configuration correct? 
- could be an issue about the experimental "Network Tunneling" feature of rancher desktop, that may could be solved in the future releases.

If you have any suggestions regarding other things we could check, they would be appreciated.

Thanks
