### ISSUE TITLE
Getting Permission Denied in Container

### ISSUE THREAD

**Issue by ryanomor** [rancher-sandbox/rancher-desktop#6200]
### Actual Behavior

After creating and running my containers using `docker compose up -d`, when I try connecting to it, I get permission issues. I open the container logs with `docker container logs $CONTAINER_ID` and get multiple lines of `chown: changing ownership of '/var/lib/postgresql/data/base/558180/558738': Permission denied`

### Steps to Reproduce

Create a docker-compose.yml that has the same config as below. Then run `docker compose up -d` and try connecting to the container and view the logs:

```yaml
version: '3.1'

services:

  postgres:
    image: postgres:11
    restart: always
    command: postgres -c 'max_connections=200'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - ${VOLUMES_ROOT}/postgres/data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
```

### Result

Can not connect to the port exposed by the container. And when I get the logs of the container, I get multiple chown permission denied errors

### Expected Behavior

Can connect to the port exposed by container. No permission denied logs in container

### Rancher Desktop Version

1.10.0

### Rancher Desktop K8s Version

v1.27.7

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey 12.7

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None
