### ISSUE TITLE
HostPath volumes on Mac

### ISSUE THREAD

**Issue by dee-kryvenko** [rancher-sandbox/rancher-desktop#678]
Consider a pod like the following:

```
metadata:
  name: foo
spec:
  containers:
    image: alpine
    name: bar
    volumeMounts:
    - mountPath: /data
      name: baz
  volumes:
  - hostPath:
      path: /Users/user/data
    name: baz
```

I'd expect this to mount `/Users/user/data` folder from my host to the container, but apparently what is getting mounted is a folder from the underlying lima VM. My understanding that there is no osxfs/Fuse driver alternative for Desktop in Rancher Desktop? Is there any plans for it? Lima seems to be capable to be translating my local paths to the default VM just fine - maybe it's a matter of missing configuration?

**Comment by dee-kryvenko** [comment]
I can confirm on vanilla Lima with k3s - this setup works as expected.

**Comment by jandubois** [comment]
There should be no difference between "vanilla Lima" and Rancher Desktop, as the latter is just using a bundled version of the former, and it does use the same mount point for `/Users/user`.

Can you provide more information about your respective setups? I assume you are using Rancher Desktop 0.4.1, but what is your "vanilla Lima" setup; what does your VM config look like? Is it based on the `examples/k3s.yaml`, or is it using some other setup?

I'll try to repro this tomorrow (or Monday), but it would be good to have as much information as possible about your setup.

**Comment by dee-kryvenko** [comment]
Rancher Desktop I installed from dmg file from https://github.com/rancher-sandbox/rancher-desktop/releases/tag/v0.4.1.

"Vanilla Lima" I insyalled with `brew install lima`:

```
> limactl --version
limactl version 0.6.4
```

I didn't do any modifications to lima, my `~/.lima/default/lima.yaml`:

```yaml
# ===================================================================== #
# BASIC CONFIGURATION
# ===================================================================== #

# Arch: "default", "x86_64", "aarch64".
# "default" corresponds to the host architecture.
arch: "default"

# An image must support systemd and cloud-init.
# Ubuntu and Fedora are known to work.
# Default: none (must be specified)
images:
  # Try to use a local image first.
  - location: "~/Downloads/hirsute-server-cloudimg-amd64.img"
    arch: "x86_64"
  - location: "~/Downloads/hirsute-server-cloudimg-arm64.img"
    arch: "aarch64"

  # Download the file from the internet when the local file is missing.
  # Hint: run `limactl prune` to invalidate the "current" cache
  - location: "https://cloud-images.ubuntu.com/hirsute/current/hirsute-server-cloudimg-amd64.img"
    arch: "x86_64"
  - location: "https://cloud-images.ubuntu.com/hirsute/current/hirsute-server-cloudimg-arm64.img"
    arch: "aarch64"

# CPUs: if you see performance issues, try limiting cpus to 1.
# Default: 4
cpus: 4

# Memory size
# Default: "4GiB"
memory: "4GiB"

# Disk size
# Default: "100GiB"
disk: "100GiB"

# Expose host directories to the guest, the mount point might be accessible from all UIDs in the guest
# Default: none
mounts:
  - location: "~"
    # CAUTION: `writable` SHOULD be false for the home directory.
    # Setting `writable` to true is possible, but untested and dangerous.
    writable: true
  - location: "/tmp/lima"
    writable: true

ssh:
  # A localhost port of the host. Forwarded to port 22 of the guest.
  # Currently, this port number has to be specified manually.
  # Default: none
  localPort: 60022
  # Load ~/.ssh/*.pub in addition to $LIMA_HOME/_config/user.pub .
  # This option is useful when you want to use other SSH-based
  # applications such as rsync with the Lima instance.
  # If you have an insecure key under ~/.ssh, do not use this option.
  # Default: true
  loadDotSSHPubKeys: true



# ===================================================================== #
# ADVANCED CONFIGURATION
# ===================================================================== #

containerd:
  # Enable system-wide (aka rootful)  containerd and its dependencies (BuildKit, Stargz Snapshotter)
  # Default: false
  system: false
  # Enable user-scoped (aka rootless) containerd and its dependencies
  # Default: true
  user: true

# Provisioning scripts need to be idempotent because they might be called
# multiple times, e.g. when the host VM is being restarted.
# provision:
#   # `system` is executed with the root privilege
#   - mode: system
#     script: |
#       #!/bin/bash
#       set -eux -o pipefail
#       export DEBIAN_FRONTEND=noninteractive
#       apt-get install -y vim
#   # `user` is executed without the root privilege
#   - mode: user
#     script: |
#       #!/bin/bash
#       set -eux -o pipefail
#       cat <<EOF > ~/.vimrc
#       set number
#       EOF

# probes:
#  # Only `readiness` probes are supported right now.
#  - mode: readiness
#    description: vim to be installed
#    script: |
#       #!/bin/bash
#       set -eux -o pipefail
#       if ! timeout 30s bash -c "until command -v vim; do sleep 3; done"; then
#         echo >&2 "vim is not installed yet"
#         exit 1
#       fi
#    hint: |
#      vim was not installed in the guest. Make sure the package system is working correctly.
#      Also see "/var/log/cloud-init-output.log" in the guest.

# ===================================================================== #
# FURTHER ADVANCED CONFIGURATION
# ===================================================================== #

firmware:
  # Use legacy BIOS instead of UEFI.
  # Default: false
  legacyBIOS: false

video:
  # QEMU display, e.g., "none", "cocoa", "sdl".
  # As of QEMU v5.2, enabling this is known to have negative impact
  # on performance on macOS hosts: https://gitlab.com/qemu-project/qemu/-/issues/334
  # Default: "none"
  display: "none"

network:
  # The instance can get routable IP addresses from the vmnet framework using
  # https://github.com/lima-vm/vde_vmnet. Both vde_switch and vde_vmnet
  # daemons must be running before the instance is started. The interface type
  # (host, shared, or bridged) is configured in vde_vmnet and not lima.
  vde:
    # vnl (virtual network locator) points to the vde_switch socket directory,
    # optionally with vde:// prefix
    # - vnl: "vde:///var/run/vde.ctl"
    #   # VDE Switch port number (not TCP/UDP port number). Set to 65535 for PTP mode.
    #   # Default: 0
    #   switchPort: 0
    #   # MAC address of the instance; lima will pick one based on the instance name,
    #   # so DHCP assigned ip addresses should remain constant over instance restarts.
    #   macAddress: ""
    #   # Interface name, defaults to "vde0", "vde1", etc.
    #   name: ""

# Port forwarding rules. Forwarding between ports 22 and ssh.localPort cannot be overridden.
# Rules are checked sequentially until the first one matches.
# portForwards:
#   - guestPort: 443
#     hostIP: "0.0.0.0" # overrides the default value "127.0.0.1"; allows privileged port forwarding
#   # default: hostPort: 443 (same as guestPort)
#   # default: guestIP: "127.0.0.1" (also matches bind addresses "0.0.0.0", "::", and "::1")
#   # default: proto: "tcp" (only valid value right now)
#   - guestPortRange: [4000, 4999]
#     hostIP:  "0.0.0.0" # overrides the default value "127.0.0.1"
#   # default: hostPortRange: [4000, 4999] (must specify same number of ports as guestPortRange)
#   - guestPort: 80
#     hostPort: 8080 # overrides the default value 80
#   - guestIP: "127.0.0.2" # overrides the default value "127.0.0.1"
#     hostIP: "127.0.0.2" # overrides the default value "127.0.0.1"
#   # default: guestPortRange: [1024, 65535]
#   # default: hostPortRange: [1024, 65535]
#   - guestPort: 8888
#     ignore: true (don't forward this port)
#   # Lima internally appends this fallback rule at the end:
#   - guestIP: "127.0.0.1"
#     guestPortRange: [1024, 65535]
#     hostIP: "127.0.0.1"
#     hostPortRange: [1024, 65535]
#   # Any port still not matched by a rule will not be forwarded (ignored)

# Extra environment variables that will be loaded into the VM at start up.
# These variables are currently only consumed by internal init scripts, not by the user shell.
# This field is experimental and may change in a future release of Lima.
# https://github.com/lima-vm/lima/pull/200
# env:
#   KEY: value

# Explicitly set DNS addresses for qemu user-mode networking. By default qemu picks *one*
# nameserver from the host config and forwards all queries to this server. On macOS
# Lima adds the nameservers configured for the "en0" interface to the list. In case this
# still doesn't work (e.g. VPN setups), the servers can be specified here explicitly.
# If nameservers are specified here, then the "en0" configuration will be ignored.
# dns:
# - 1.1.1.1
# - 1.0.0.1

# ===================================================================== #
# END OF TEMPLATE
# ===================================================================== #
```

Well, I did change `writable: true` at some point but initially I tested with `writable: false` and it was the same.

Inside Lima I installed K3s like so:

```
curl -sfL https://get.k3s.io | sh -
```

And then grabbed the output from `sudo k3s kubectl config view --raw` to my Mac host.

I can't find neither lima binary nor lima.yaml that Rancher Desktop is using to compare - what path should it be under and how would I `shell` into Docker Desktop VM? My suspicion is that its VM or its `mounts` are different from vanilla.

**Comment by jandubois** [comment]
I've verified that this is indeed broken in RD 0.4.1, but it does work in the latest development builds that will become RD 0.5.0 within the next couple of days.

I strongly suspect that this is due to RD 0.4.1 bundling an older version of Lima, and I think the issue was fixed by https://github.com/lima-vm/lima/pull/247 which was merged into Lima just 11 days ago.

**Comment by jandubois** [comment]
> can't find neither lima binary nor lima.yaml that Rancher Desktop is using to compare - what path should it be under and how would I `shell` into Rancher Desktop VM? My suspicion is that its VM or its `mounts` are different from vanilla.

Yes, RD uses a small Alpine image instead of the large Ubuntu cloud image, and is stripped down just to the essentials needed to run Rancher Desktop workloads.

You can find the instance data in RD 0.4.1 under `~/Library/State/rancher-desktop/lima/rancher-desktop`.

In the next release it will move to the more standard location of `~/Library/Application Support/rancher-desktop/lima/0` (the instance name has changed from `rancher-desktop` to just `0` because socket names are limited to 103 characters on macOS).

You can access the VM by setting `LIMA_HOME`, e.g. (for 0.5.0, adjust for 0.4.1 as needed):

```console
$ LIMA_HOME=~/Library/Application\ Support/rancher-desktop/lima limactl shell 0 uname -a
Linux lima-rancher-desktop 5.10.61-0-virt #1-Alpine SMP Mon, 30 Aug 2021 07:41:25 UTC x86_64 Linux
```

If you break anything inside the VM, you get to keep all the pieces. 😸

**Comment by dee-kryvenko** [comment]
> If you break anything inside the VM, you get to keep all the pieces. 😸

😆 

Thanks for the help - indeed this is what my `~/Library/State/rancher-desktop/lima/rancher-desktop/lima.yaml` looks like:

```yaml
mounts:
  - location: /Users/user/Library/Caches/rancher-desktop/k3s
    writable: false
```

That explains it.

**Comment by jandubois** [comment]
> That explains it.

Indeed. I forgot that RD 0.4.1 doesn't map the usual directories. In 0.5.0 the mounts will be like this:

```yaml
mounts:
  - location: /Users/jan/Library/Caches/rancher-desktop/k3s
    writable: false
  - location: "~"
    writable: false
  - location: /tmp/rancher-desktop
    writable: true
```
