### ISSUE TITLE
Inconsistent behavior with Wasm enabled

### ISSUE THREAD

**Issue by divya-mohan0209** [rancher-sandbox/rancher-desktop#6785]
### Actual Behavior

**Context:**

I tried out the SpinKube x Rancher Desktop integration detailed on [this page](https://www.spinkube.dev/docs/spin-operator/tutorials/integrating-with-rancher-desktop/). It works seamlessly for the hello-world application detailed there & on the [Fermyon blog](https://www.fermyon.com/blog/spinkube-rancher).

However, when I tried installing some of the other complex templates and containerizing them, such as

- [Spin Docusaurus](https://github.com/VamshiReddy02/spin-docusaurus/)
- [Spin Zola](https://github.com/karthik2804/spin-zola/),
- [Spin Qwik Frontend](https://github.com/vanvuongngo/qwik-wasm)

or even templates of my own

- [Rancher Docs template](https://github.com/divya-mohan0209/docs-template-docusaurus/)

there is inconsistent behaviour, i.e. they sometimes work and most of the time, they don't. 

This is when the spin applications themselves work fine on my machine.

### Steps to Reproduce

This is [a repo](https://github.com/divya-mohan0209/docs-template-docusaurus/) with the template I created that has the steps listed.

The app, itself, works locally. But when containerizing it using SpinKube, it doesn't work.

I've also tried other more complex (and official) templates listed on the Fermyon website like

- [Spin Docusaurus](https://github.com/VamshiReddy02/spin-docusaurus/)
- [Spin Zola](https://github.com/karthik2804/spin-zola/),
- [Spin Qwik Frontend](https://github.com/vanvuongngo/qwik-wasm),

but they don't work.

### Result

The pods enter the **CrashLoopBackOff** stage and are terminated with the following message: **Last state: Terminated with 137: Error**.  

### Expected Behavior

The containerized apps should work and the pods should come up. However, this behavior is wildly inconsistent.

### Additional Information

**Last state: Terminated with 137: Error** - Since this error typically points to an error with memory. I tried increasing the memory assigned to pods and it didn't help. 

I tried resetting the Kubernetes cluster and restoring Rancher Desktop to its factory settings (individually, of course). None of those approaches helped and in fact, had the opposite effect. If the templates were working before the factory reset or the cluster reset, they stopped working after. (Of course, I shouldn't have tried to fix what wasn't broken by resetting it 😆 But I did it anyway for the sake of reproducibility)

Lastly, I wasn't sure where the error was, so I filed it against this repo. I'll also open an issue against the SpinKube GitHub repo.

### Rancher Desktop Version

1.13.1

### Rancher Desktop K8s Version

1.29.3, 1.28.9

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

Sonoma 14.1

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by divya-mohan0209** [comment]
[Issue opened against the SpinKube repo](https://github.com/spinkube/spin-plugin-kube/issues/80)

**Comment by saiyam1814** [comment]
Another example not working 


clone this https://github.com/fermyon/ai-examples/tree/main/sentiment-analysis-ts

do 
```spin build 
spin registry push ttl.sh/demosenti:1h 
```
Create certificate
`curl -sfL https://curl.se/ca/cacert.pem -o ca-certificates.crt &&  kubectl create secret generic spin-ca --from-file=ca-certificates.crt`
 
Add spinapp.yaml
```
apiVersion: core.spinoperator.dev/v1alpha1
kind: SpinApp
metadata:
  name: spin-sentiment-analysis
spec:
  image: "ttl.sh/demosenti:1h"
  executor: containerd-shim-spin
  replicas: 2
  runtimeConfig:
    llmCompute:
      type: "remote_http"
      options:
        - name : "url"
          value: "https://fermyon-cloud-gpu-uguyedt7.fermyon.app"
        - name: "auth_token"
          value: "addtoken"
  volumes:
    - name: ca-certs
      secret:
        secretName: spin-ca
        items:
          - key: ca-certificates.crt
            path: ca-certificates.crt
  volumeMounts:
    - name: ca-certs
      mountPath: "/etc/ssl/certs/ca-certificates.crt"
      readOnly: true
      subPath: ca-certificates.crt
```
