### ISSUE TITLE
Increase open file limit in the VM / inside containers

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#713]
Report on user-slack: https://rancher-users.slack.com/archives/C0200L1N1MM/p1633033996169800

> pod ulimits are too low for my use case. Specifically open files. Any recommended way to increase it?

Default setting for `ulimit -n` is 1024, same as in most distros. Should we increase it?

**Comment by stephenpope** [comment]
Trying rancher-desktop and hit these errors with OOTB Helm charts for these applications ..

ElasticSEarch
```
1]: max file descriptors [4096] for elasticsearch process is too low, increase to at least [65535]
ERROR: Elasticsearch did not exit normally - check the logs at /usr/share/elasticsearch/logs/elasticsearch.log
```
Neo4J
```
WARNING: Max 1024 open files allowed, minimum of 40000 recommended. See the Neo4j manual.
```

RabbitMQ
```
rabbitmq 17:46:43.55 INFO  ==> Initializing RabbitMQ...
/opt/bitnami/scripts/librabbitmq.sh: line 750: ulimit: open files: cannot modify limit: Operation not permitted
```

**Comment by jandubois** [comment]
Since nobody indicated which platform they are using, I'm just assuming macOS (or Linux) now. If you are on Windows, this will not work:

Create an `~/Library/Application Support/rancher-desktop/lima/_config/override.yaml` file with a provisioning script:

```yaml
provision:
- mode: system
  script: |
    #!/bin/sh
    cat <<'EOF' > /etc/security/limits.d/rancher-desktop.conf
    * soft     nofile         82920
    * hard     nofile         82920
    EOF
```

Stop and restart Rancher Desktop, and you should have updated limits in your containers. I've verified this with RabbitMQ; after the restart the container started up automatically.

I've also checked the `dockerd` configuration, which seems to have a larger `nofile` limit by default.
