### ISSUE TITLE
custom registry

### ISSUE THREAD

**Issue by fragolinux** [rancher-sandbox/rancher-desktop#721]
hi
what's the correct way to add a custom registry.yaml file to RD k3s?
in k3d i do something like this: `--volume "$cfgDir/registries.yaml:/etc/rancher/k3s/registries.yaml"`
thanks in advance

**Comment by jandubois** [comment]
There is no "correct" way (as in "supported" way) to do this right now, but you could try to add the mount manually. Edit `~/Library/Application\ Support/rancher-desktop/lima/0/lima.yaml` after you have been running Rancher Desktop at least once, but while the app is stopped.

Locate the `mounts` section and add an additional entry at the end:

```yaml
mounts:
  - location: ~/Library/Caches/rancher-desktop/k3s
    writable: false
  - location: "~"
    writable: false
  - location: /tmp/rancher-desktop
    writable: true
  - location: "/etc/rancher/k3s"
    writable: false
```

It is important that the entry is added at the end; otherwise it will be overwritten by Rancher Desktop on the next start. And you cannot map directories to a different location, so you will have to create `/etc/rancher/k3s` on your host as `root`, and put the `registries.yaml` file in there (it is not possible to just mount the file; you have to mount the directory).

After you saved the `lima.yaml` file, restart `Rancher Desktop`. It should now use your configured registries. Please report back if this actually works, as I haven't tested it. 😸 

Eventually we will add proper support for this functionality in the UI, but for now this ~~hack~~workaround should give you the functionality you need.

**Comment by jandubois** [comment]
I assumed this was about macOS; if you are running on Windows, this would need a different approach.

**Comment by fragolinux** [comment]
> I assumed this was about macOS; if you are running on Windows, this would need a different approach.

yes, sorry for the missing information: talking about macos, indeed... thanks :)

**Comment by fragolinux** [comment]
after closed RD, added those 2 lines at the end of the mounts section of lima.yaml, and run:
```
sudo mkdir -p /etc/rancher/k3s
sudo nano /etc/rancher/k3s/registries.yaml
```
put my registries in there, saved, i have now:
```
sudo ls -la /etc/rancher/k3s
total 8
drwxr-xr-x  3 root  wheel    96  4 Ott 18:05 .
drwxr-xr-x  3 root  wheel    96  4 Ott 18:04 ..
-rw-r--r--  1 root  wheel  2111  4 Ott 18:05 registries.yaml
```
now RD does not start anymore... about 5 minutes stuck in STARTING KUBERNETES...

![image](https://user-images.githubusercontent.com/21192010/135886406-2da68499-5abf-46e0-9efa-4aad4a5ec30d.png)

**Comment by jandubois** [comment]
I'm sorry, I forgot that `k3s` needs to be able to write to that directory to create `k3s.yaml`, so this approach won't work.

I tried to copy the file in via a provisioning script, but that doesn't work either because at that point the directories have not yet been mounted.

What did work was embedding the `registries.yaml` inside the `lima.yaml` file as a provisioning script:

```yaml
provision:
...
  - mode: system
    script: |
      #!/bin/sh
      set -eux
      mkdir -p /etc/rancher/k3s
      cat <<EOF >/etc/rancher/k3s/registries.yaml
      mirrors:
        "my.company.registry:5000":
          endpoint:
          - http://my.company.registry:5000
      EOF
```

As before, this has to be added at the end. And if Rancher Desktop during an upgrade adds another provisioning script, your script will have to be added back after the upgrade.
