### ISSUE TITLE
Unable to mount hostPath in Rancher Desktop Kubernetes

### ISSUE THREAD

**Issue by SledgeHammer01** [rancher-sandbox/rancher-desktop#7299]
### Actual Behavior

I'm coming from Docker Desktop K8s, and had the PV/PVCs working there.

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /run/desktop/mnt/host/c/users/xxx~1/.airflow
```

And then for this particular application:

```
        dags:
          persistence:
            enabled: true
            existingClaim: airflow
```

I've set Rancher Desktop to use the dockerd engine, so I was expecting a drop in replacement. There doesn't seem to be much information on how to do this in Rancher. Is it possible??

### Steps to Reproduce

N/A

### Result

Hostpaths are not getting mounted.

### Expected Behavior

That host paths get mounted.

### Rancher Desktop Version

1.15.0

### Rancher Desktop K8s Version

1.30.3

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None
