### ISSUE TITLE
Allow easy way to enable client-ip forward in rancher desktop on macos

### ISSUE THREAD

**Issue by SDAdham** [rancher-sandbox/rancher-desktop#7541]
### Problem Description

I installed rancher desktop, enabled kubernetes, installed ingress as following:
```
helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
helm repo update
helm upgrade --install nginx-ingress ingress-nginx/ingress-nginx --namespace ingress-nginx --create-namespace --values ./values.yaml
```
and the config of `values.yaml` is as following:
```
controller:
  extraArgs:
    enable-ssl-passthrough: true
  # config:
  #   use-proxy-protocol: 'true'
  #   use-forwarded-headers: 'true'
    # use-forward-headers: 'true'
    # compute-full-forward-for: 'true'
  # hostNetwork: true
  service:
    # type: "NodePort"
    externalTrafficPolicy: Local
    # externalTrafficPolicy: Cluster
  replicaCount: 1
```
No matter how much I tried or played with this, I cannot get any workaround to pass client real ip.

### Proposed Solution

Please provide either documentation or way to help with this.
