### ISSUE TITLE
Enable UDP protocol in iptable scanning

### ISSUE THREAD

**Issue by Nino-K** [rancher-sandbox/rancher-desktop#7762]
As of this [PR](https://github.com/rancher-sandbox/rancher-desktop/pull/7723) we have enabled iptables scanning for some of the entries in `CNI-DN`. However, using the lima's iptable's scanning code it can only return a boolean for TCP as discussed [here.](https://github.com/rancher-sandbox/rancher-desktop/pull/7723#discussion_r1833169840). As part of this issue, we should investigate how the entries in `CNI-DN` are created and how to enable `UDP` since the current [condition](https://github.com/rancher-sandbox/rancher-desktop/blob/eca49fb26ffaa24dfba021d6c790069780cb7206/src/go/guestagent/pkg/iptables/iptables.go#L82) only checks for `TCP`.

**Comment by mikeseese** [comment]
I have not found a specific clarification of if there are options other than `TCP` but after looking at the CNI port map plugin, [a `-p` option is always provided](https://github.com/containernetworking/plugins/blob/6e7fb60738998431c0be3f3b21b96cb1e7043f1a/plugins/meta/portmap/portmap_iptables.go#L201). The [regex pattern](https://github.com/lima-vm/lima/blob/adc5a71943b72949aefcc2b9eb8ffb1f7fe2dce5/pkg/guestagent/iptables/iptables.go#L34) used to ultimately create the `TCP` bool [condition](https://github.com/rancher-sandbox/rancher-desktop/blob/eca49fb26ffaa24dfba021d6c790069780cb7206/src/go/guestagent/pkg/iptables/iptables.go#L82) looks for the inclusion of `-p tcp` to set that bool. So if `-p tcp` is not found, then `-p <something else>` **must** be specified (the regex wouldn't match otherwise and the CNI portmap plugin code linked also specifies that it always provides the `-p` option).

While yes, there are [many other protocols at the transport layer](https://en.wikipedia.org/wiki/List_of_IP_protocol_numbers), I feel like assuming !TCP == UDP would be a value add and not detrimental of the assumption was wrong; because otherwise the protocol wouldn't succeed because it's not TCP or UDP (in which case, would still not work since it's not TCP).

I'd love to have this feature in as it's blocking a customer from remotely accessing UDP game servers running in the K3S cluster via RD.

There is a simple fix to lima to add another boolean for UDP if you're not keen on making the above assumption.

**Comment by mikeseese** [comment]
I got [this assumption working](https://github.com/RedwoodMMO/rancher-desktop/commit/693392de8daa545ce4ac7210339ada4f4dd9b870) and made an [installer](https://github.com/RedwoodMMO/rancher-desktop/releases/tag/1.17.1) to unblock my customer.

I tested this with this TCP/UDP echo server:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: echo-server
  namespace: realm-default
spec:
  containers:
    - name: echo-server
      image: vhiribarren/echo-server
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 4001
          hostPort: 12345
          protocol: UDP
        - containerPort: 5001
          hostPort: 12346
          protocol: TCP
      resources:
        limits:
          cpu: 50m
          memory: 128Mi
        requests:
          cpu: 50m
          memory: 128Mi
```

and used [this JS port of nc](https://www.npmjs.com/package/nc) to test it. I also saw the UDP port mapped properly using TCP Viewer.
