### ISSUE TITLE
After migrating to 1.17 docker compose ignores depends_on if there is extends block in the service definition

### ISSUE THREAD

**Issue by DiverOfDark** [rancher-sandbox/rancher-desktop#8062]
### Actual Behavior

we have docker compose file which define service something like this:
```
  myservice:
    extends:
      file: docker-compose.base-service.yml
      service: base
    image: '...'
    labels:
      - "a=b"
    environment:
      ENV: value
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      traefik:
        condition: service_healthy
```

when I try to run `docker-compose up -d myservice` - then only `myservice` is started, and mysql/rabbit/traefik are skipped.
If I remove extends block and inline the contents - everything works as before.

in 1.16 this worked as expected.

### Steps to Reproduce

Create a docker compose file with extends and service. specify depends_on in docker-compose (not extends).

### Result

Instead of bringing up container with dependencies - I see only this. Also note the total count of services is 0.

```
docker compose up -d myservice
[+] Running 1/0
 ✔ Container folder-myservice-1  Running     
```

### Expected Behavior

I expect all dependent containers are started and waited for if health check if specified:

```
docker compose up -d myservice
[+] Running 1/4
 - Container folder-traefik-1            Starting
 - Container folder-mail-1                Starting
 - Container folder-mysql-1               Starting
✔ Container folder-myservice-1            Running 
```

### Rancher Desktop Version

1.17

### Rancher Desktop K8s Version

n/a

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11. Same behavior on MacOS with Arm

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jandubois** [comment]
Can you please include a working repro case, i.e. a compose file we can run locally to reproduce the issue?

**Comment by jandubois** [comment]
I'm also confused that you say you are using `containerd (nerdctl)`, but then show `docker` example commands. Please provide the exact configuration that has this problem!

**Comment by DiverOfDark** [comment]
minimal example:

docker-compose.yml:
```
services:
  myservice-a:
    extends:
      file: base-file.yml
      service: base
    depends_on:
      myservice-b:
        condition: service_healthy

  myservice-b:
    extends:
      file: base-file.yml
      service: base
```

base-file.yml:
```
services:
  base:
    image: rabbitmq:latest
```

if you try to `docker compose up myservice-a`  -> then service `myservice-b` is not started.

Re containerd - my bad, I was wrong, it was dockerd, but I believe problem might be in docker compose plugin.
