### ISSUE TITLE
tolerations on lima-rancher-desktop node.yaml

### ISSUE THREAD

**Issue by wibed** [rancher-sandbox/rancher-desktop#8473]
### Actual Behavior

try to add tolerations.

```yaml
      tolerations:
        - key: "node.kubernetes.io/disk-pressure"
          operator: "Exists"
          effect: "NoSchedule"
```

to
```yaml
spec:
  podCIDR: 10.42.0.0/24
  podCIDRs:
    - 10.42.0.0/24
  providerID: k3s://lima-rancher-desktop
  tolerations:
      - key: "node.kubernetes.io/disk-pressure"
          operator: "Exists"
          effect: "NoSchedule"
```

the save button blinks and closes the submenu.

### Steps to Reproduce

open the cluster dashboard

and edit the configuration yaml for the node.
add necessary lines as seen above.

### Result

the save button blinks and closes the submenu.

### Expected Behavior

the save button to become green the submenu to stay open and awaiting new instructions

### Rancher Desktop Version

1.18.2

### Rancher Desktop K8s Version

1.32.0

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

Sequoia

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None
