### ISSUE TITLE
mount local path as volume

### ISSUE THREAD

**Issue by wibed** [rancher-sandbox/rancher-desktop#8474]
### Actual Behavior

i try to mount the local path from the host onto the vm or atleast expose the directory on the path to be mounted as a volume in a pod.

i added necessary configuration to `~/Library/Application\ Support/rancher-desktop/lima/_config/override.yaml`
```
mounts:
- location: /Users/wibe/Documents/projects
  writable: true
```

restarted rancher desktop

start a deployment which does mount said directory onto itself:
```yaml
...
      containers:
          volumeMounts:
          - mountPath: /workspaces
            name: task-vol
...
      volumes:
        - name: task-vol
          hostPath:
            path: "/Users/wibe/Documents/projects"
            type: "Directory"
``` 

### Steps to Reproduce

try to mount a pod as seen above with a volume mount pointing to a local path  on macos

### Result

```shell
  Warning  FailedScheduling  40s   default-scheduler  0/1 nodes are available: 1 node(s) had untolerated taint {node.kubernetes.io/disk-pressure: }. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling.
```

### Expected Behavior

to mount the directory and make it accessible for mutation within the pod

### Rancher Desktop Version

1.18.2

### Rancher Desktop K8s Version

1.32.0

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

Sequoia

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None
