### ISSUE TITLE
custom cluster cidr

### ISSUE THREAD

**Issue by wibed** [rancher-sandbox/rancher-desktop#8540]
### Actual Behavior

i try to set the cidr of the shared network through settings in the override.yaml

here is the file:
```yaml
env:
  # needed for cilium
  INSTALL_K3S_EXEC: '--flannel-backend=none --disable-network-policy --cluster-cidr=172.31.0.0/16'

mountType: virtiofs
mounts:
  - location: /Users/wibe/Documents/projects
    writable: true

networks:
  - lima: rancher-desktop-shared
    mode: shared
    interface: rd1
    gateway: 172.31.0.1
    netmask: 255.255.0.0
  - lima: rancher-desktop-bridged_en6
    mode: bridged
    interface: rd0

provision:
  # needs root to mount
  - mode: system
    script: |
      #!/bin/sh
      set -e

      # needed for cilium
      mount bpffs -t bpf /sys/fs/bpf
      mount --make-shared /sys/fs/bpf

      mkdir -p /run/cilium/cgroupv2
      mount -t cgroup2 none /run/cilium/cgroupv2
      mount --make-shared /run/cilium/cgroupv2/
```

from here i get the configuration parameters i try to set:
https://github.com/rancher-sandbox/rancher-desktop/blob/2ff3669ff4b7c7e5d99cf23ff4eb3f8974dbdf20/src/k8s-engine/lima.ts#L117

yet after reset i am confronted with the following error and the default configuration (as seen in the image) persists.

```shell
rdctl shell sudo k3s kubectl config view --raw > kubeconfig
WARN[0000] Non-strict YAML detected; please check for typos  comment="override file \"/Users/wibe/Library/Application Support/rancher-desktop/lima/_config/override.yaml\"" error="[15:5] unknown field \"netmask\"\n  12 |     mode: shared\n  13 |     interface: rd1\n  14 |     gateway: 172.31.0.1\n> 15 |     netmask: 255.255.0.0\n           ^\n  16 |   - lima: rancher-desktop-bridged_en6\n  17 |     mode: bridged\n  18
```

![Image](https://github.com/user-attachments/assets/e64f3200-c82f-47c3-936e-9edf574a00f5)

i keep removing fields until i arrive at the original configuration.
i cant find any resources on how to configure the networks.

i list some related issues here. theyre might not be related at all:
- https://github.com/rancher-sandbox/rancher-desktop/issues/7591

on a side note: i tried using daemon.json but use effectively containerd

### Steps to Reproduce

-

### Result

-

### Expected Behavior

-

### Rancher Desktop Version

1.18.2

### Rancher Desktop K8s Version

1.32.2

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

Sequoia

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None
