### ISSUE TITLE
Add support for MSYS style path names on Windows to docker-proxy

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#8775]
Docker Desktop supports MSYS style path names like `/c/users/joe` instead of `C:\Users\joe` in bind mounts, and also in docker-compose files.

I've looked at the `docker/cli`, `moby/moby`, and `moby/buildkit` repos, and couldn't find any code that would be responsible for normalising the paths.

Testing shows that they don't work with Rancher Desktop:

```console
C:\Users\SUSE>echo "Hello world" >hello.txt

C:\Users\SUSE>docker run -it --rm -v .:/host alpine cat /host/hello.txt
"Hello world"

C:\Users\SUSE>docker run -it --rm -v c:/users/suse:/host alpine cat /host/hello.txt
"Hello world"

C:\Users\SUSE>docker run -it --rm -v /c/users/suse:/host alpine cat /host/hello.txt
cat: can't open '/host/hello.txt': No such file or directory
```

It looks like the `wsl-helper docker-proxy` would be the obvious place to implement this translation.

Also add a test case to BATS (both for `-v` bind mounts, and for `docker-compose` file usage).

**Comment by rfay** [comment]
I'll follow up with a better, simpler repro case, and attempt to narrow this down a bit. Thanks!

**Comment by rfay** [comment]
I studied this and was baffled by DDEV's conversion to old MSYS/Docker Toolbox mount styles. I found a bunch of old Docker Toolbox workarounds in DDEV, but none of them were related. Then I discovered that we had COMPOSE_CONVERT_WINDOWS_PATHS=1, which causes the MSYS-style path conversion. I guess this is also from Docker Toolbox days. 

In simple testing with docker-compose to try to demonstrate the problems discussed in [slack thread](https://rancher-users.slack.com/archives/C0200L1N1MM/p1749651227298549) I was unable to reproduce, mounts worked fine. A docker-compose.yaml like

```yaml
services:
  rddemo:
    image: debian
    volumes:
      - .:/mnt/rddemo
    command:
      - sleep
      - infinity
```

with `docker-compose config` was transformed properly to

```yaml
name: rddemo
services:
  rddemo:
    command:
      - sleep
      - infinity
    image: debian
    networks:
      default: null
    volumes:
      - type: bind
        source: C:\Users\randy\tmp\rddemo
        target: /mnt/rddemo
        bind:
          create_host_path: true
networks:
  default:
    name: rddemo_default
```

It was only with COMPOSE_CONVERT_WINDOWS_PATHS=true that we had the odd tranformation.

Apparently Docker Desktop preserved the needed MSYS paths for mounts for Docker Toolbox backward compatibility.

It may or may not be worth implementing support in Rancher Desktop, but I don't think it's going to be needed for DDEV, given tests passing on 
* https://github.com/ddev/ddev/pull/7375

The only issue now is whether I want to get automated testing for Rancher Desktop going.
