### ISSUE TITLE
Traefik Dashboard

### ISSUE THREAD

**Issue by v2kiran** [rancher-sandbox/rancher-desktop#896]
Hi 
how do we enable the dashboard for the traefik ingress controller?

OS: windows 11
App: Rancher Desktop

**Comment by vovtz** [comment]
Same question for macOS.

**Comment by charlywazzap** [comment]
not sure if there is an easier way but you can create this with kubectl

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: dashboard
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`traefik.localhost`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
```

and you can access via http://traefik.localhost/dashboard/#/

hope this helps
