### ISSUE TITLE
[Documentation] Clarification about using locally built images

### ISSUE THREAD

**Issue by Sebor** [rancher-sandbox/rancher-desktop#952]
**For feature requests, describe what you'd like to add or change**
At the present time it's not clear how to use locally built images (by `nerdctl build`) in k8s manifests.
There is a phrase on main RD [site](https://rancherdesktop.io/) `The container images you build can be run by Kubernetes immediately without the need for a registry` and no more info about that

**To Reproduce**
1. build image `nerdctl build -t local/my-app:latest .`
2. Deploy simple manifest:
    ```yaml
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: my-app-deployment
      labels:
        app: my-app
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: my-app
      template:
        metadata:
          labels:
            app: my-app
        spec:
          containers:
            - name: my-app
              image: local/my-app:latest
    ```
    by command:
    ```bash
    kubectl apply -f my-app.yaml
    ```
3. Get events
    ```bash
    kubectl get events
    ```
    See error something like this:
    ```text
    Failed to pull image "local/my-app:latest": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/local /my-app:latest": failed to resolve reference "docker.io/local/my-app:latest": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
    ```

**Setup (please complete the following information):**
 - OS: MacOS Monterey
 - Rancher Desktop version: 0.6.1
 - Kubernetes version: 1.21.6
